### ISSUE TITLE
Option to hide country and opt out of country rankings

### ISSUE THREAD

**Issue by 0xallie** [ppy/osu-web#10465] opened 2023-08-14 13:50 UTC
It might be nice to have an option to hide your country, e.g. for privacy reasons or not wanting to represent your country. This would opt you out of country rankings on pp leaderboards and beatmap score leaderboards, and probably make you ineligible for any country-based tournaments as well.

**Comment by cl8n** [comment] 2023-08-25 20:24
I think this is okay but there should be a community poll to see if most others are okay with it too. country flags are all over the place in osu and so this would be a large change to how profiles work

**Comment by cl8n** [comment] 2023-09-06 02:53
also duplicate of #8033 :broom:

**Closed by cl8n** 2023-09-06 02:53 UTC
Labels: area:settings
