### ISSUE TITLE
"WIP"/"Ranked" etc. beatmap tag appearing behind the preview button on the profile's beatmap section

### ISSUE THREAD

**Issue by GVmG** [ppy/osu-web#3002] opened 2018-04-13 09:56 UTC
Idk how to explain it exactly in words so here's two examples: https://rain.s-ul.eu/WOwKHZmn.png - https://rain.s-ul.eu/g7MnBKWN.png

In the top left, you can see the tag thingy behind the "stop playback" icon. It does hide when the mouse hovers the header, but it doesn't if the preview is playing and the mouse isn't hovering on it.

**Comment by nekodex** [comment] 2018-04-13 11:04
duplicate of #2706

**Closed by nekodex** 2018-04-13 11:04 UTC
