### ISSUE TITLE
Slidercount on beatmaps overlap the semi-transparent background

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu-web#4300] opened 2019-04-02 14:31 UTC
Image Preview:
[https://i.imgur.com/e5BWqBx.png](https://i.imgur.com/e5BWqBx.png)

Beatmap:
[https://osu.ppy.sh/beatmapsets/29157#osu/156352](https://osu.ppy.sh/beatmapsets/29157#osu/156352)

**Comment by Joehuu** [comment] 2019-08-01 02:54
Duplicate of #1879.

**Closed** 2019-08-03 14:46 UTC
Labels: beatmap listing, bug
