### ISSUE TITLE
Mapper on beatmap info redirects to wrong user

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#8837] opened 2022-04-22 12:28 UTC
The mapper of [this beatmap](https://osu.ppy.sh/beatmapsets/3#osu/91) has the **user_id** `141`. However, clicking on the mapper redirects you to the profile of a person with the **username** `141`.

![image](https://user-images.githubusercontent.com/22381687/164713738-9c935e76-f2f8-4701-9d7c-e083e12c13a4.png)

**Comment by peppy** [comment] 2022-04-23 02:56
This is really weird. Did something regress with user links? I thought that IDs are always preferred to usernames for the new routing..

**Comment by nanaya** [comment] 2022-04-23 03:02
the user is deleted and due to regression, the link is still created and it falls back to username look up (to be fixed by #8802 )

**Comment by nanaya** [comment] 2022-04-26 03:28
Should be fixed on next release.

**Closed by nanaya** 2022-04-26 03:28 UTC
Labels: area:beatmap-info, priority:0
