### ISSUE TITLE
Issue with font size on new site in map description.

### ISSUE THREAD

**Issue by maridius98** [ppy/osu-web#2223] opened 2018-01-16 21:52 UTC
It was actually working well when I edited the description on old site. Now that I've decided to edit the description on new site, without messing with font size, this happened. When I look at the description at the old site, it also transformed into this where the bigger font size doesn't work. This doesn't apply on forums as far as I've tested. Same applies to all font sizes available. 

![image](https://user-images.githubusercontent.com/34574278/35013463-cd3d37bc-fb0d-11e7-943e-d1fede1d63df.png)

This is the format

![image](https://user-images.githubusercontent.com/34574278/35014160-fe5891b4-fb0f-11e7-9386-7f63a96d1e75.png)

**Comment by dorothy3242** [comment] 2018-01-16 21:55
This is from the [/size] tag going across multiple lines, please see https://github.com/ppy/osu-web/issues/268 and https://github.com/ppy/osu-web/issues/1666
if you edit it via. the forum stub, it will fix itself. I recommend avoiding editing descriptions and similar things on the new website until whenever this is fixed.

**Comment by peppy** [comment] 2018-01-16 23:39
Closing as duplicate of #268.

**Closed by peppy** 2018-01-16 23:39 UTC
Labels: forum
