### ISSUE TITLE
Add possibility of multiple difficulty owners

### ISSUE THREAD

**Issue by kongehund** [ppy/osu-web#11152] opened 2024-04-09 17:09 UTC
When a collab difficulty is made by two mappers (uploader and guest), it is customary to put the guest mapper as difficulty owner. This gives both mappers direct credit if the song gets ranked, such that the guest mapper will have the map show up on their profile as a guest participation beatmap.

It is currently only possible to assign a single difficulty owner, even though some collab difficulties are created by three or more mappers.

This means only two mappers will get direct linked credit on their profile, which is clearly a wrongful indication.

To solve the problem, I suggest adding the functionality of assigning multiple difficulty owners to a beatmap difficulty.

**Comment by Joehuu** [comment] 2024-04-09 18:41
Duplicate of https://github.com/ppy/osu-web/issues/7602

**Closed by Joehuu** 2024-04-09 18:41 UTC
