### ISSUE TITLE
seprate beatmap packs in different areas for each gamemode 

### ISSUE THREAD

**Issue by mugiishiro** [ppy/osu-web#9551] opened 2022-11-28 16:18 UTC
so basically that it's easier to search for beatmap packs without having to scroll through every other gamemode. could also be done for loved/ranked maps but the amount of loved is probably to low.

**Comment by WindowsMeosu** [comment] 2022-11-28 21:47
isn't that what mode=osu!/taiko/ctb/mania and status=ranked/approved/loved/unranked is for?

**Comment by Joehuu** [comment] 2022-12-01 04:20
Duplicate of https://github.com/ppy/osu-web/issues/4247

**Closed by Joehuu** 2022-12-01 04:20 UTC
