### ISSUE TITLE
Redirecting forum pages

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3805] opened 2018-10-15 07:32 UTC
If you click on "osu!" in this line:
![unknown](https://user-images.githubusercontent.com/32525896/46935988-22d94380-d05d-11e8-93eb-dfd9708fd43d.png)
it sends you to https://osu.ppy.sh/community/forums#forum-1 , but it should be https://osu.ppy.sh/community/forums/1

same with Beatmaps, Others, Language Specific
https://osu.ppy.sh/community/forums/12
https://osu.ppy.sh/community/forums/11
https://osu.ppy.sh/community/forums/23

**Comment by nanaya** [comment] 2018-10-15 07:42
That's intentional. They're top level forums and don't directly contain posts.

**Comment by peppy** [comment] 2018-10-17 08:59
Seems to be correct as-is. Closing as intended behaviour.

**Closed by peppy** 2018-10-17 08:59 UTC
