### ISSUE TITLE
7 forum posts, when there is actually one

### ISSUE THREAD

**Issue by MrCheatEugene** [ppy/osu-web#10973] opened 2024-02-05 13:49 UTC
Hi there. Just saw this bug:
![image](https://github.com/ppy/osu-web/assets/40684650/d7dc1310-92e7-49a2-bb6b-f34fb95bf0a1)
![image](https://github.com/ppy/osu-web/assets/40684650/e721404e-93e3-4cf0-b811-1affd99b37a8)

**Comment by cl8n** [comment] 2024-02-06 00:19
duplicate of what was identified in https://github.com/ppy/osu-web/issues/7821#issuecomment-883239406

**Closed by cl8n** 2024-02-06 00:19 UTC

**Comment by cl8n** [comment] 2024-02-06 08:52
it'll be resolved by the suggestion in that comment, even though the issue title isn't about the exact same thing
