### ISSUE TITLE
Toggles should save state

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4434] opened 2019-05-10 06:54 UTC
For instance, the toggle on user profile to collapse the rank graph will not remember between page loads of logins.

**Comment by Joehuu** [comment] 2019-07-16 06:03
Description is a duplicate of #3967. Other toggles should be clearly said in separate issues.

**Comment by peppy** [comment] 2019-08-08 05:18
Was any progress made on this?

**Comment by notbakaneko** [comment] 2019-08-27 05:48
Other toggles should have their own issue

**Closed by notbakaneko** 2019-08-27 05:48 UTC
Labels: user profile, ux
