### ISSUE TITLE
Symbols not centered correctly

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#2816] opened 2018-03-26 12:17 UTC
Actually positioned a bit odd. I mean the symbols I'm holding my cursor on: https://lya.s-ul.eu/IUEBtK2a.png, https://lya.s-ul.eu/on8Qx0GP.png, https://lya.s-ul.eu/utRRmc0v.png (view size in browser: 100% on all screenshots)
Changing view size changes their position a bit but that doesn't help much.

Also not sure if it's just me? And if so, what can I do?

**Comment by nanaya** [comment] 2018-03-26 12:25
Duplicate of #1574.

**Closed by nanaya** 2018-03-26 12:25 UTC
