### ISSUE TITLE
Add a way to join channels directly through chat page

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#8541] opened 2022-01-25 20:32 UTC
currently, the only way to add channels to the site chat is by adding them from lazer chat which is extremely counter-intuitive, there should be a way where you can easily join them from the site.

I tried slash commands and they don't work either.

**Comment by mmodules** [comment] 2022-01-25 20:37
Duplicate of https://github.com/ppy/osu-web/issues/4661

**Closed** 2022-01-27 12:24 UTC
