### ISSUE TITLE
Inconsistency in username shown

### ISSUE THREAD

**Issue by celerih** [ppy/osu-web#5079] opened 2019-10-08 17:02 UTC
Search and profiles use the username of the user at the time of qualification
![](https://celerih.s-ul.eu/2I4Nvae1.png)
![](https://celerih.s-ul.eu/vKZVQgRB.png)

But beatmap pages use the user's current username
![](https://celerih.s-ul.eu/j2OSomRQ.png)

Given how the username at time of qualification is also what is used in-game, bringing beatmap pages in line with the rest of the site and game would be ideal

**Comment by dorothy3242** [comment] 2019-10-08 17:07
Duplicate of https://github.com/ppy/osu-web/issues/1975

**Closed** 2019-10-09 02:22 UTC
