### ISSUE TITLE
Empty forum search query should return all results

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#7538] opened 2021-04-29 01:18 UTC
There used to be the ability to view all posts by one user in a certain thread via 

http://osu.ppy.sh/forum/search.php?author_id=4635891&t=625397.  Its equivalent now is 

https://osu.ppy.sh/home/search?mode=forum_post&query=&username=abraker&topic_id=625397. 

However, using that it complains that the search query is empty. I believe this was most used in the [mafia subforums](https://osu.ppy.sh/community/forums/posts/4369007) to get an isolated examination on a player, but I'm sure it has other uses as well.

**Comment by nanaya** [comment] 2021-04-29 04:02
Duplicate of #3059. In the meantime, it's way more inconvenient to use but there's https://osu.ppy.sh/users/4635891/posts?topic_id=625397

**Closed by nanaya** 2021-04-29 04:02 UTC

**Comment by nekodex** [comment] 2021-04-29 04:14
You can also search for `*` and have it do what you're after, e.g:
https://osu.ppy.sh/home/search?mode=forum_post&query=*&username=abraker&topic_id=625397
