### ISSUE TITLE
[profile] BBCode breaks after a map is updated

### ISSUE THREAD

**Issue by wial663** [ppy/osu-web#11724] opened 2024-12-07 20:32 UTC
Essentially, adding any profile BBCode completely breaks right after you update a mapset, making you have to copy and paste the BBCode again for it to be formatted properly.

![image](https://github.com/user-attachments/assets/e00f2212-e668-4f6d-a73c-d59c8e0a1d92)

**Comment by Joehuu** [comment] 2024-12-07 22:54
Duplicate of https://github.com/ppy/osu-web/issues/7051

**Closed by Joehuu** 2024-12-07 22:54 UTC
