### ISSUE TITLE
The hr line can be almost invisible on different page sizes

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2720] opened 2018-03-17 11:53 UTC
![](https://puu.sh/zJvMS/e347c5a3e1.png)

https://osu.ppy.sh/beatmapsets/707811/discussion

**Comment by Joehuu** [comment] 2018-03-17 15:34
Occurs everywhere that has this line. Seems to be there, but the color disappeared. Can occur at different zooms. Should change the title.
![](https://puu.sh/zJB9i/e8a9c44cce.png)
![](https://puu.sh/zJB7o/f49aa08ee9.png)
![](https://puu.sh/zJB1H/d9657fad7c.png)
![](https://puu.sh/zJB1Z/4f8e90cd13.png)

**Comment by Joehuu** [comment] 2019-07-16 07:15
Can't reproduce now.

**Comment by nanaya** [comment] 2019-07-16 09:51
Nice, it's fixed by itself, I guess :ghost:

**Closed by nanaya** 2019-07-16 09:51 UTC
Labels: design
