### ISSUE TITLE
Display star rating in Feature Request forum listing

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3768] opened 2018-10-08 20:07 UTC

**Comment by dorothy3242** [comment] 2018-10-08 20:11
Duplicate of https://github.com/ppy/osu-web/issues/1173

**Comment by TPGPL** [comment] 2018-10-08 20:15
i think voting on feature request is something *different* than displaying the stat on forum listing

**Comment by dorothy3242** [comment] 2018-10-09 01:49
yes, except it explicitly is mentioned in the opener "display current star priority at a minimum"...

**Comment by peppy** [comment] 2018-10-09 04:05
Closing as duplicate of #1173.

**Closed by peppy** 2018-10-09 04:05 UTC
