### ISSUE TITLE
play history dates don't show correctly when translated to spanish

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu-web#8845] opened 2022-04-24 15:11 UTC
I think this might happen with other languages as well, I can't see the date at all in the play history section in user profiles, since the year is cut off

![image](https://user-images.githubusercontent.com/41755816/164983076-b756e0ad-81fc-4af6-a4e8-0509bd34ef5c.png)

**Comment by Joehuu** [comment] 2022-04-24 15:59
Duplicate of https://github.com/ppy/osu-web/issues/6896

**Closed by Joehuu** 2022-04-24 15:59 UTC

**Comment by Gonzalo-Bruna** [comment] 2022-04-24 16:04
ah sorry, I couldn't find the issue.
