### ISSUE TITLE
[profile=<id>] BB code tag isn't correctly handled on beatmap submission

### ISSUE THREAD

**Issue by dotremilie** [ppy/osu-web#11466] opened 2024-09-02 16:02 UTC
`[profile=<id>]<username>[/profile]` BB code isn't correctly handled on beatmap submission. 

On submission:

![obraz](https://github.com/user-attachments/assets/e159d894-76dc-4d8d-aeaf-d1c8bf62f1f8)

It may not be related to `osu-web`, but some `osu-api` endpoint that handles beatmap submission. It most likely uses a different logic that doesn't handle `[profile=<id>]<username>[/profile]`, but only `[profile]<username>[/profile]`. Any `PATCH /beatmapsets/<beatmapset_id>` with `description` body fixes it. 

Here I remove id on Kuki1537 link and keep the rest with id:

![obraz](https://github.com/user-attachments/assets/f7c2dc54-4d1c-4166-b863-553fadc96e45)

Result on web:

![obraz](https://github.com/user-attachments/assets/6fd36296-d25a-44c8-975e-046c87326610)

![obraz](https://github.com/user-attachments/assets/e3053df5-d6ff-4adf-af5b-73867b19c5d7)

After `PATCH /beatmapsets/2241059`:

![obraz](https://github.com/user-attachments/assets/a9565abc-da8e-496b-b26e-6a610259fb4d)

![obraz](https://github.com/user-attachments/assets/ac2737e5-85e3-43ab-b1df-f5bf8e7e053e)

As you can see `PATCH /beatmapsets/2241059` added the user `id` to the `profile` tag and then displayed correctly.

**Comment by nanaya** [comment] 2024-09-02 16:28
duplicate of #7051

**Closed by nanaya** 2024-09-02 16:28 UTC
