### ISSUE TITLE
Mutual tag not updating until refresh

### ISSUE THREAD

**Issue by DMills94** [ppy/osu-web#3131] opened 2018-05-04 17:46 UTC
On the old version of the website, adding someone as a friend instantly said if it was a mutual friend, or just a friend. The new website requires a refresh for the mutual appears.

Perhaps it could appear upon clicking?

Current:
![2018-05-04_18-44-26](https://user-images.githubusercontent.com/31848108/39643089-7636d1cc-4fcb-11e8-95fd-ae05ecb17636.gif)
 (white screen is page reload)

**Comment by DMills94** [comment] 2018-05-04 17:50
My bad - didn't check if it was already a mentioned issue https://github.com/ppy/osu-web/issues/1549

**Comment by peppy** [comment] 2018-05-06 12:34
Duplicate of #1549.

**Closed by peppy** 2018-05-06 12:34 UTC
