### ISSUE TITLE
Sort your Favourite Beatmaps

### ISSUE THREAD

**Issue by mugiishiro** [ppy/osu-web#9552] opened 2022-11-28 17:22 UTC
It would be cool to have a function that you could switch the order of your favourite beatmaps without having to unfavourite and favourite the map again.

**Comment by worthlessnut9** [comment] 2022-11-30 22:05
like a similar system to sorting your pinned plays would a nice way to implement this

**Comment by Joehuu** [comment] 2022-12-01 04:27
Duplicate of https://github.com/ppy/osu-web/issues/4346

**Closed by Joehuu** 2022-12-01 04:27 UTC
