### ISSUE TITLE
Add portuguese as a language tag for beatmaps

### ISSUE THREAD

**Issue by doggoboat** [ppy/osu-web#9601] opened 2022-12-07 01:13 UTC
I was searching for beatmaps earlier today and I ended up noticing that portuguese isn't available as a language tag for beatmaps, and wondered if it would be possible to add it as one, since currently there are more maps with full portuguese vocals using the metadata tag than maps with leaderboards featuring swedish vocals and using the language tag.

Kind regards, and thanks for reading my issue!
[delta](https://osu.ppy.sh/users/8523723)

**Comment by Joehuu** [comment] 2022-12-07 01:30
Duplicate of https://github.com/ppy/osu-web/issues/6963

**Closed by Joehuu** 2022-12-07 01:30 UTC
