### ISSUE TITLE
Dates should be specified rather than rounded up

### ISSUE THREAD

**Issue by Serizawa-Haruki** [ppy/osu-web#5220] opened 2019-10-31 23:25 UTC
In many places, such as the top score listing, the date is often rounded up by a lot which gives users incorrect information about when the score was set. The same goes for other places on the website such as the modding discussion page, when a map was last updated etc.
In the following example it says "2 years ago" although it's only been 1 year, 6 months and 3 days. That's a pretty significant difference, so either using "more than a year ago" or simply using only the specific date would be more accurate.
![chrome_2019-11-01_00-17-02](https://user-images.githubusercontent.com/43621386/67992701-14e16b00-fc3e-11e9-97c6-63ef2390ef7e.png)

**Comment by nanaya** [comment] 2019-11-01 01:59
Duplicate of #3762.

**Closed by nanaya** 2019-11-01 01:59 UTC
