### ISSUE TITLE
Modding panel layout issues

### ISSUE THREAD

**Issue by Shmiklak** [ppy/osu-web#6475] opened 2020-08-12 18:48 UTC
The textarea for the mod posts becomes too wide and runs out of the actual form box in case the mod itself is huge

https://i.imgur.com/KLddwWS.png

Not like a big issue, yet it makes modding beatmap uncomfortable when you need to explain your point in details and it was fine in before until some recent updates (like a day or two ago)

**Comment by gagahpangeran** [comment] 2020-08-13 00:08
Duplicate of #6447

**Closed** 2020-08-13 09:50 UTC
