### ISSUE TITLE
Add a link to osu!lazer's GitHub releases page in the download osu! section of the website

### ISSUE THREAD

**Issue by Bambinexx** [ppy/osu-web#8512] opened 2022-01-15 20:32 UTC
Or even add a direct download on the website without having to go on github. Maybe add it as an option where you can choose between stable and lazer, it would help newcomers discover the client, as I still see some people today that have been around for years and still doesn't know what Lazer is. Also, the tutorial to install osu! on OS X hasn't been updated in 3 years, maybe updating or removing it seems like a good idea, as well as adding documentation on how to install stable osu! on Linux (that would have helped me a lot when I discovered this game first).

**Comment by bdach** [comment] 2022-01-15 20:46
see https://github.com/ppy/osu-web/issues/8246

**Comment by Walavouchey** [comment] 2022-10-08 14:15
duplicate of the above

**Comment by peppy** [comment] 2022-10-08 14:30
https://github.com/ppy/osu-web/issues/8246

**Closed by peppy** 2022-10-08 14:30 UTC
