### ISSUE TITLE
negative notification count

### ISSUE THREAD

**Issue by blessed2541** [ppy/osu-web#6455] opened 2020-08-07 19:17 UTC
![Capture](https://user-images.githubusercontent.com/27869100/89680439-3ec56d80-d8f3-11ea-9c89-0e3ed3989c4c.PNG)

The bug is very minor. Sometimes my notification count shows a negative number. I do not know the cause.

**Comment by tybug** [comment] 2020-08-07 19:19
seems to be a resurgence of #5598

**Comment by gagahpangeran** [comment] 2020-08-08 05:03
Could you reproduce it again and tell the steps?

**Comment by peppy** [comment] 2020-08-10 06:54
ping @notbakaneko

**Comment by blessed2541** [comment] 2020-08-10 11:31
The bug seems to not be happening as much anymore. It used to happen when i
just went to  https://osu.ppy.sh/ and then pressed on "My Profile"

V V pon., 10. avg. 2020 ob 08:55 je oseba Dean Herbert <
notifications@github.com> napisala:

**Comment by notbakaneko** [comment] 2020-08-11 05:38
Do you browse the site with multiple tabs?

**Comment by blessed2541** [comment] 2020-08-11 10:23
Usually only 1 osu tab, but multiple others like youtube, facebook,
twitter...

**Comment by notbakaneko** [comment] 2020-08-13 11:04
This is looking more like incorrect clock time on the client (outside of extension shenanigans) - for the count to go negative now, the notification client needs to receive a notification `read` event for a notification that it hasn't loaded yet; however, the client ignores `read` events from before it was initialized, marking an already read notification doesn't send any `read` event; the client basically has to be initialized with a timestamp _before the notification was marked as read_, but somehow with the _notification already marked as read_ and yet _also_ receive the `read` event.

**Comment by peppy** [comment] 2020-08-29 09:09
Does this mean a page refresh would fix the display? Or just waiting for the time zone to catch up?

**Comment by notbakaneko** [comment] 2020-08-31 00:20
refreshing always gets the correct count

**Comment by notbakaneko** [comment] 2020-09-13 15:54
cause for this looks likely to be how chat messages are handled via LIO #6639

**Closed by notbakaneko** 2020-09-13 15:54 UTC
Labels: area:notifications
