### ISSUE TITLE
`No comments yet` disclaimer not showing if there's a pinned comment

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#8007] opened 2021-08-14 16:44 UTC
comment section with a single (pinned) comment:

![image](https://user-images.githubusercontent.com/19843905/129453332-ea7cebd9-50a2-49a6-90d2-d5c9b8c284cf.png)

comment section without any comments:

![image](https://user-images.githubusercontent.com/19843905/129453353-edeb14c9-013c-42d8-b0b1-99601774f669.png)

**Comment by bdach** [comment] 2021-08-14 16:48
For what it's worth I don't think it makes sense to show "no comments" if there *is* a comment, even if it's a pinned one?

**Comment by TPGPL** [comment] 2021-08-14 16:50
yeah though i think it looks kinda wrong with how it is right now

**Comment by smoogipoo** [comment] 2021-08-16 04:46
@arflyte please provide insight into whether this is intended, or if "no comments" should still show up if there's a pinned comment.

**Comment by arflyte** [comment] 2021-08-23 06:35
Yeah, we shouldn't show 'No comments yet' if there are pinned comments.

**Comment by smoogipoo** [comment] 2021-08-23 06:45
Closing as intended.

**Comment by nanaya** [comment] 2021-08-23 06:50
Does it not look weird though being just an empty section?

**Comment by peppy** [comment] 2021-08-23 08:12
It definitely does look weird and has actually thrown me off once or twice. Not sure on how it should look though.

**Comment by arflyte** [comment] 2021-08-23 08:48
Another alternative is to make it show "No other comments yet" or something along the tline.

**Comment by peppy** [comment] 2021-08-23 09:21
Might work better. Let's keep this open for now.

**Comment by nanaya** [comment] 2023-05-24 07:20
Fixed in #10218.

**Closed by nanaya** 2023-05-24 07:20 UTC
Labels: type:ux, area:comments
