### ISSUE TITLE
unicode characters are entered twice in beatmap discuss review

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-web#9294] opened 2022-09-19 16:03 UTC
![image](https://user-images.githubusercontent.com/34775378/191061660-a0c4bcaa-37ab-4aa0-8b0d-35af2d230dcd.png)
Entering non-English characters (even symbols) here will be entered twice
![image](https://user-images.githubusercontent.com/34775378/191061870-bb67ef7c-964f-4e47-a270-2b0f63f70ecd.png)
after press enter
![image](https://user-images.githubusercontent.com/34775378/191061963-4497dcbf-aa3f-45a4-84d3-be19ad552460.png)

**Comment by peppy** [comment] 2022-09-20 05:26
I cannot reproduce the issue.

Please state your browser / operating system

**Comment by notbakaneko** [comment] 2022-09-20 06:22
This should be a duplicate of #6097

**Closed by notbakaneko** 2022-09-20 06:22 UTC
Labels: area:beatmap-discussions, type:browser-issue
