### ISSUE TITLE
My osu! profile stats on the website are empty

### ISSUE THREAD

**Issue by Fatalution** [ppy/osu-web#9684] opened 2022-12-27 23:35 UTC
My osu! profile when viewed from browser shows that I have 0 pp scores, 0% accuracy and no SS/S/A etc plays.
However, it does show that I have 1193 plays, total score obtained and such.

Now, should that work like this for the lazer.ppy.sh? I have only played osu!lazer, not stable osu!

Video or screenshot showing the problem: https://imgur.com/a/kLissIz

**Comment by Glinte** [comment] 2022-12-27 23:44
As far as I know, it is intended that some data (play count, play time, ...) be synced to your main profile.

**Comment by Fatalution** [comment] 2022-12-27 23:46
> As far as I know, it is intended that some data (play count, play time, ...) be synced to your main profile.

Yes, but both my main and lazer profiles are equally empty. 
You can check for yourself here: 
https://osu.ppy.sh/users/21766417
https://lazer.ppy.sh/users/21766417

**Comment by mangkoran** [comment] 2022-12-28 12:15
I also noticed this behaviour. I have 0 ranked scores in stable, yet several in lazer. But I have no ranks in lazer website.

https://osu.ppy.sh/users/15289216
https://lazer.ppy.sh/users/15289216

**Comment by Fatalution** [comment] 2022-12-29 09:11
@mangkoran that's correct. I don't believe I even have any scores from stables at all, let alone ranked ones. 

Still, the profile should reflect all my stats...no?

**Comment by mangkoran** [comment] 2022-12-29 09:13
@Fatalution It should be. I have contacted @peppy on Twitter and linked this issue.

**Comment by Fatalution** [comment] 2022-12-29 09:24
Would love to have a link for the tweet, can't find it @mangkoran

**Comment by Fatalution** [comment] 2023-01-02 16:40
Welp, I guess we're screwed

**Comment by bdach** [comment] 2023-01-02 16:43
@Fatalution please have some patience. this issue is roadmapped as one to be looked at in short order.

**Comment by Fatalution** [comment] 2023-01-02 22:03
> @Fatalution please have some patience. this issue is roadmapped as one to be looked at in short order.

Wowee! That's awesome to hear, all good :)

**Comment by mangkoran** [comment] 2023-01-04 05:49
I believe this @peppy tweet indicates this has been solved? https://twitter.com/ppy/status/1610501884368007168

**Comment by Fatalution** [comment] 2023-01-04 06:32
> I believe this @peppy tweet indicates this has been solved? https://twitter.com/ppy/status/1610501884368007168

Will check a bit later. If so, will close the issue

**Comment by peppy** [comment] 2023-01-04 07:32
Yep, in theory this should be fixed. Please report back after setting a score!

**Comment by mangkoran** [comment] 2023-01-04 08:04
@peppy I just recently setting a score but it seems my rank is not updated yet.

**Comment by peppy** [comment] 2023-01-04 08:11
Could you please link the page you are viewing, and also share which lazer version you are running?

**Comment by mangkoran** [comment] 2023-01-04 08:17
https://lazer.ppy.sh/users/15289216

2022.1228.0-lazer

**Comment by peppy** [comment] 2023-01-04 08:25
Thanks, I'm investigating further.

**Comment by peppy** [comment] 2023-01-04 08:27
It looks like there was some caching issues. I've re-run calculation on your profile and it looks to be in a good state now.

**Comment by mangkoran** [comment] 2023-01-04 08:28
Confirmed. Now I know I am a lowly 5-digit.

Thank you peppy and team <3

**Comment by Fatalution** [comment] 2023-01-04 08:29
> It looks like there was some caching issues. I've re-run calculation on your profile and it looks to be in a good state now.

Any chance you can do the same thingy for mine? :)

https://lazer.ppy.sh/users/15289216

**Comment by mangkoran** [comment] 2023-01-04 08:29
However, "Ranked Score" seems 0. Is this intended?
![image](https://user-images.githubusercontent.com/57625126/210514213-e66dfbce-9244-4fcf-a8fc-603d995b5aca.png)
And no country ranking.
![image](https://user-images.githubusercontent.com/57625126/210514265-fc96cea8-ae78-4290-8512-9228f7d5dc8b.png)

**Comment by peppy** [comment] 2023-01-04 08:38
Ranked score is not accounted for by lazer just yet. We'll backfill that eventually.

Not sure about country ranking @nanaya can you check on that and see if it's something my end or web's end?

**Comment by nanaya** [comment] 2023-01-04 08:45
`country_acronym` attribute for the stats entry was blank.

**Comment by Fatalution** [comment] 2023-01-04 11:32
@peppy @nanaya thanks to both of you, the issue is now gone on my end. The only thing that is empty is Ranked Score entry - but as was mentioned above, it is as intended for now.

Thank you very much! It's incredibly awesome to see this level of personal involvement from the devs when it comes to issues like this. I'm kinda new to osu, so yeah :D

Issue can be closed I guess, unless there are others experiencing the same problems

**Comment by Shirou27** [comment] 2023-01-04 12:53
Mine too doesn't have Country Ranking

https://lazer.ppy.sh/users/23892930

**Comment by peppy** [comment] 2023-01-04 15:27
Going to close this as fixed. I've run a once-off repair on country acronym population which should fix missing country rankings over the next 30 minutes.

**Closed by peppy** 2023-01-04 15:27 UTC

**Comment by DarkQuiet** [comment] 2023-03-08 20:30
> Going to close this as fixed. I've run a once-off repair on country acronym population which should fix missing country rankings over the next 30 minutes.

I guess, i have the same problem 
https://lazer.ppy.sh/users/32964866

**Comment by Fatalution** [comment] 2023-03-11 11:29
Yup, @peppy , seems like the problem still applies to newly created accounts that only play Lazer. Something is wrong server- or database-side

**Comment by Fatalution** [comment] 2023-03-11 11:30
> 
> 
> 
> 
> 
> 
> > Going to close this as fixed. I've run a once-off repair on country acronym population which should fix missing country rankings over the next 30 minutes.
> 
> 
> 
> I guess, i have the same problem 
> 
> https://lazer.ppy.sh/users/32964866

I've tagged @peppy, let's see if the issue gets reopened
