### ISSUE TITLE
Allow for search of users with multiple mods in leaderboard.

### ISSUE THREAD

**Issue by chika-osu** [ppy/osu-web#4697] opened 2019-07-21 05:15 UTC
![5508A650-974C-40CF-BEE5-4A7BB6BC1AC7](https://user-images.githubusercontent.com/34539452/61587272-83337d80-abb9-11e9-865b-c095bdbb1b4d.png)

You can search for players in a leaderboard with a single common mod like Nightcore, but you cant search with multiple mods like HDNCFL.

**Comment by Joehuu** [comment] 2019-07-21 05:30
Duplicate of #2950.

**Comment by Cynplytholowazy** [comment] 2019-07-21 05:31
Duplicate of #4674.

**Closed** 2019-07-22 08:38 UTC
