### ISSUE TITLE
Beatmap points of failure chart needs axis and legend

### ISSUE THREAD

**Issue by Slayer95** [ppy/osu-web#4315] opened 2019-04-09 03:19 UTC
There is no clue of what the X and Y coordinates are, as well as the meaning of the color encoding.

![Screenshot](https://i.imgur.com/20Iqv97.png)

**Comment by Slayer95** [comment] 2019-04-09 04:57
This could use https://github.com/ppy/osu/issues/4175, so that clicking on the chart triggers an ``osu://`` link and opens the selected point in the game.

That would be the best way to convey the meaning of the X axis, and I presume it would be useful for the author to analyze the beatmap stats for future enhancements.

**Comment by Slayer95** [comment] 2019-04-24 08:09
Actually, I just found out about ``osu://edit/`` links. That should be enough!

**Comment by Joehuu** [comment] 2019-05-22 04:15
Duplicate of #2099.

**Comment by TPGPL** [comment] 2019-11-08 23:46
should be closed as duplicate?

**Closed** 2019-11-09 01:08 UTC
Labels: beatmap listing, design, ux

**Comment by Slayer95** [comment] 2019-11-09 01:35
@peppy , the other issue is tagged as Backlog. Was the downgrading of the issue's priority intended?
