### ISSUE TITLE
Change order of icons on user card

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#6030] opened 2020-05-19 16:07 UTC
It's weird and confusing that the friends icon changes position between users. 
In this case, if you only look real quick, it almost looks like I'm a mutual with peppy, since the supporter icon has a similar color to mutals. Making it so the friends icon is always the first one fixes this.
|Before|![](https://i.imgur.com/jH0F527.png)|
|-------|-----|
|After|![](https://i.imgur.com/3RC04Mg.png)|

I didn't find an issue about this, but it might have been my keywords.

**Comment by Joehuu** [comment] 2020-05-19 16:33
Duplicate of https://github.com/ppy/osu-web/issues/2914. Has been a problem since the old design.

**Comment by peppy** [comment] 2020-06-01 10:20
Closing as duplicate for the time being.

**Closed by peppy** 2020-06-01 10:20 UTC
