### ISSUE TITLE
Text selection is wonky

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu-web#6273] opened 2020-07-06 18:58 UTC
Whenever I try to select text, either other stuff gets selected with it, or the thing I'm trying to select becomes the _one_ thing that isn't.
I'm using Windows 10 19041.330 and Chrome 84.0.4147.68.

![image](https://user-images.githubusercontent.com/15932372/86629281-76c35300-bfcb-11ea-9c7d-5af0b1cc8bf6.gif)

**Comment by bdach** [comment] 2020-07-06 19:14
Duplicate of #5001

**Comment by peppy** [comment] 2020-07-13 22:28
As a workaround, try selecting from after or inside the element, not before. Chrome can't figure what you are trying to select if you select from way outside the field.

This is a hugely common web thing and not local to our page (although we should try and fix these cases if we can).

**Closed by peppy** 2020-07-13 22:28 UTC
