### ISSUE TITLE
Supporter tag icon is not consistent on the web

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2695] opened 2018-03-14 19:42 UTC
Pick the transparent or pink one.
~Also the usercard one links to [supporter features page](https://osu.ppy.sh/home/support), should be nice to redirect to the [buying page](https://osu.ppy.sh/store/products/supporter-tag) with the person shown on the usercard.
![usercard](https://user-images.githubusercontent.com/35318437/37426956-1813332e-2785-11e8-966d-5acfbe6445e3.png)
![profile](https://user-images.githubusercontent.com/35318437/37426958-1b11c9e6-2785-11e8-8f37-a27ab21c17f3.png)~
Edit: Okay do the original issue and link the profile icon to the features page to make this not a duplicate, since it doesn’t link to anything.

**Comment by jacksonisiah** [comment] 2018-03-14 19:45
if both should link somewhere, they should link to the supporter features page over the buying page.

**Comment by Joehuu** [comment] 2018-03-14 19:52
I mean to gift that player with that button for easy access. You have access to the features page in the navigation and the button in the dashboard.

**Comment by jacksonisiah** [comment] 2018-03-15 01:19
still don't agree. if I was a newbie and I was exploring some profiles, I would rather like to know what the little heart icon meant than to gift someone else some money.

**Comment by nanaya** [comment] 2018-03-15 06:09
Considering the icon only appears for supporter, linking it to gift page means no link for non-supporter. Also duplicate of #1587.

**Comment by Joehuu** [comment] 2018-03-15 14:49
Changed the side issue that the supporter icon on the profile should link to somewhere(features page) now.

**Comment by arflyte** [comment] 2018-05-22 06:21
Use the latter design, without the pink fill.

**Closed** 2018-05-22 07:12 UTC
Labels: design, proposal

**Comment by Joehuu** [comment] 2019-04-26 20:03
It's different again. Not counting supporter page as it isn't the new design.
![](https://puu.sh/DkkCG/333aedfcc7.jpg)
![](https://puu.sh/DkkCM/7fd16c6167.jpg)
