### ISSUE TITLE
BBCode editor that supports live view instead of using the preview button and coding again on errors.

### ISSUE THREAD

**Issue by kyleacuna** [ppy/osu-web#10845] opened 2024-01-07 04:31 UTC
Saw a reddit post on this topic.
https://www.reddit.com/r/osugame/comments/17jhhwn/looking_for_a_bbcode_editor_that_supports/

I was hoping to see that osu! will provide this live view for bbcode so that when we post forum or editing our "me!", we don't need to rely on clicking the preview button again and again.

// This issue was entered on ppy/osu and since it is web-based issue, I was thinking to just put it here too.

**Comment by cl8n** [comment] 2024-01-18 22:37
duplicate of #8119

**Closed by cl8n** 2024-01-18 22:37 UTC
