### ISSUE TITLE
Activity event page

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu-web#6450] opened 2020-08-07 13:03 UTC
I have proposal to create activity event page like [this page](https://osu.ppy.sh/p/events) in old website.

![Screenshot from 2020-08-07 19-13-32](https://user-images.githubusercontent.com/4964985/89644937-09b11f00-d8e3-11ea-93ed-4d293da3b3ab.png)

Currently osu have #announce channel in chat but it's a bit hidden and it's not there by default if you don't open it in lazer. Also, that channel shows fewer activity than activity feed page in old site.

![Screenshot from 2020-08-07 19-13-04](https://user-images.githubusercontent.com/4964985/89644968-19306800-d8e3-11ea-8c9e-7f68e737df44.png)

Rough design like this, with highlight if there's new rank 1 or new ranked map.

![image](https://user-images.githubusercontent.com/4964985/89648129-edb07c00-d8e8-11ea-8e5a-1010349c6e11.png)

**Comment by TPGPL** [comment] 2020-08-07 13:21
duplicate of #3678

**Closed** 2020-08-07 13:51 UTC
