### ISSUE TITLE
Explicit tag on featured artist listings

### ISSUE THREAD

**Issue by Aiquo** [ppy/osu-web#7946] opened 2021-07-30 07:29 UTC
Any featured artist that has a song on their listings with explicit content on it (e.g. **[S3RL - MTC](https://osu.ppy.sh/beatmapsets/716630)**) should also receive the explicit tag on the featured artist listings in order to keep the consistency with the maps in the beatmap section. It could also serve to "warn" people beforehand, I suppose.

So, something like this...
![](https://cdn.discordapp.com/attachments/725238892973916172/870555527824965672/unknown.png)
...shouldn't be hard to implement, hopefully.

**Comment by cl8n** [comment] 2024-01-19 06:57
duplicate of  #7041

**Closed by cl8n** 2024-01-19 06:57 UTC
Labels: proposal, area:featured-artist
