### ISSUE TITLE
Beatmap discussions with many praise can take seconds to filter

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6603] opened 2020-09-05 03:39 UTC
Initial load or filter changes on [this map](https://osu.ppy.sh/beatmapsets/1212452/discussion/-/generalAll) can take seconds to apply. I'd say this can likely be improved with minimal effort.

**Comment by maotovisk** [comment] 2020-09-05 07:12
It not only happens when having a lot praises tho. https://osu.ppy.sh/beatmapsets/970063/discussion, for example, takes a lot of time to filter the timeline. So i would say it is a general discussions-wide issue.

**Comment by peppy** [comment] 2020-09-05 07:28
Yes, didn't mean to say it was *only* praise. Just a large number of items.

**Comment by nanaya** [comment] 2020-09-07 04:34
This is duplicate of #6285.

**Closed by nanaya** 2020-09-07 04:34 UTC
Labels: area:beatmap-discussions, type:performance
