### ISSUE TITLE
Differing BPM's not shown within same mapset on live website

### ISSUE THREAD

**Issue by CThreee** [ppy/osu-web#4888] opened 2019-09-03 19:42 UTC
They're both shown the same as the lowest diff's 162.35. The egg+++ and egg++ diff are 211 and 195.
![Screenshot from 2019-09-03 15-13-59](https://user-images.githubusercontent.com/24468026/64201868-b1b1a300-ce5d-11e9-97a7-40deede16d28.png)
![Screenshot from 2019-09-03 15-15-26](https://user-images.githubusercontent.com/24468026/64201872-b4ac9380-ce5d-11e9-957b-6cc9914ba407.png)

**Comment by VenixOSU** [comment] 2019-09-03 21:37
Well, beatmaps are meant to use one song so using BPM value from one difficulty makes sense here I believe.

**Comment by peppy** [comment] 2019-09-04 01:52
For now this is intended, yes.

**Comment by nanaya** [comment] 2019-09-11 08:06
Duplicate of #3404.

**Closed by nanaya** 2019-09-11 08:06 UTC
