### ISSUE TITLE
Top 50 scores should be highlighted in recent feed as it was on the old site

### ISSUE THREAD

**Issue by Rdzeniu** [ppy/osu-web#8877] opened 2022-05-09 05:32 UTC
I can't be the only one that liked when my top 50 score was standing out on my profile.
Of course it is not necessary and probably most of you guys don't care but I think it's cool 
![before](https://user-images.githubusercontent.com/1345628/167346382-7e74a9b1-e689-49ff-bf06-0547ee4285ec.png)
![opera_WnZp8kY3xT](https://user-images.githubusercontent.com/1345628/167346385-ea2256c7-234f-4e8f-a38e-1cd3e55517b2.png)

**Comment by peppy** [comment] 2022-05-09 06:35
@arflyte do you have anything in mind for how this would be displayed? We already have the metadata but it's not being used by osu-web yet. If it helps, the importance of a single item in this list is denoted by a numeric value, so for instance getting in the top 10 may be even more important than the ones shown in the screenshot (i think in old web the whole row's text would scale up).

**Comment by arflyte** [comment] 2022-05-09 07:09
Hmm, alright. I'll try to highlight top 10, 50 and 100. Would probably play around with the colours to highlight it.

**Comment by Wieku** [comment] 2022-05-09 19:23
It seems to be a duplicate of #2801

**Closed** 2022-05-09 19:40 UTC
Labels: area:user-profile, priority:3
