### ISSUE TITLE
Having `Classic scoring` activated gives `Strict Tracking` plays extra score on web leaderboard

### ISSUE THREAD

**Issue by amnezziaa** [ppy/osu-web#11446] opened 2024-08-21 12:50 UTC
## Example 1

Map: https://osu.ppy.sh/beatmapsets/65#osu/155

### Screenshots

With `Lazer mode` and without `Classic scoring`: 
![image](https://github.com/user-attachments/assets/142a4c95-25fe-4442-8f45-7ee3be7f1f42)

With `Lazer mode` and with `Classic scoring`: 
![image](https://github.com/user-attachments/assets/af3e68b7-9df5-451c-bb49-50d8e9389ab2)

You can see that my score gets awarded extra score compared to beef wellington's one as I'm using `Strict Tracking`. However it only happens when `Classic Scoring` is checked.

## Example 2

Map: https://osu.ppy.sh/beatmapsets/393995#osu/857603

### Screenshots

With `Lazer mode` and without `Classic scoring`: 
![image](https://github.com/user-attachments/assets/02f13efc-47ab-406e-83ce-d03ddca01b50)

With `Lazer mode` and with `Classic scoring`: 
![image](https://github.com/user-attachments/assets/a30d0028-b38d-4929-bc90-4bb369432422)

You can see that lilybannanas9's score has extra score compared to the other as he is using `Strict Tracking`. By the way, his score is not even catapulted to first place which makes it even weirder.

**Comment by nanaya** [comment] 2024-08-21 20:12
I don't know the details but it looks like the mod increases object count which results in higher converted score.

**Comment by peppy** [comment] 2024-08-22 05:25
@ppy/team-client

**Comment by bdach** [comment] 2024-08-22 05:45
Duplicate of https://github.com/ppy/osu/issues/19232

**Closed by bdach** 2024-08-22 05:45 UTC
Labels: external component
