### ISSUE TITLE
double click link error

### ISSUE THREAD

**Issue by lnd1** [ppy/osu-web#11007] opened 2024-02-16 01:11 UTC
(for some reason only works for some links) If you click a link to another part of the website multiple times you will get an error because it adds extra things to the URL that isn't intended. For example if you went to the wiki under the help tab and clicked the Installation link once the URL becomes (https://osu.ppy.sh/wiki/en/Client/Installation) but if you accidentally click it twice you get (https://osu.ppy.sh/wiki/en/Client/Client/Installation) and you get a page error because that page doesn't exist
image here
![osu](https://github.com/ppy/osu-web/assets/160193438/0874042b-0da1-4b78-b3bd-d1c01638e9d5)

**Comment by Joehuu** [comment] 2024-02-16 01:16
Duplicate of https://github.com/ppy/osu-web/issues/10662

**Closed by Joehuu** 2024-02-16 01:16 UTC
