### ISSUE TITLE
The lack of the playcount per month feature in the new web

### ISSUE THREAD

**Issue by CaptainTristana** [ppy/osu-web#2147] opened 2018-01-02 09:25 UTC
Title

**Comment by peppy** [comment] 2018-01-02 09:26
Could you please provide more details, such as where you are expecting to see this?

**Comment by CaptainTristana** [comment] 2018-01-02 09:28
https://puu.sh/ySzLy/a759c13274.jpg Im refering to this, as it is not currently in the new web, as of my expectations, it would be really cool to have a general graph which could be expanded to specify each months playcount when hover over that month :p

**Comment by peppy** [comment] 2018-01-03 03:04
Not sure why this was closed, as it is a valid issue.

**Comment by dorothy3242** [comment] 2018-02-14 06:51
duplicate of https://github.com/ppy/osu-web/issues/2147  ? Still needed though either way.

**Comment by peppy** [comment] 2018-02-14 06:53
This is #2147. Did you mean to duplicate another issue?

**Comment by dorothy3242** [comment] 2018-02-14 06:54
yes because i apparently can't copypaste correctly
i meant https://github.com/ppy/osu-web/issues/1157

**Comment by peppy** [comment] 2018-02-14 06:55
Closing as duplicate of #1157.

**Closed by peppy** 2018-02-14 06:55 UTC
Labels: user profile
