### ISSUE TITLE
Add ability to moved / dragged favorite beatmaps in profile

### ISSUE THREAD

**Issue by Aikyuu-Chan** [ppy/osu-web#8962] opened 2022-05-27 06:10 UTC
Something like this:

Original version:
![](https://i.imgur.com/4Mmota5.png)

Feature Request version:
![](https://i.imgur.com/d9nAkJL.png)

Sorry for bad edit and thank you very much.

**Comment by Joehuu** [comment] 2022-12-01 04:26
Duplicate of https://github.com/ppy/osu-web/issues/4346

**Closed by Joehuu** 2022-12-01 04:26 UTC
Labels: area:user-profile, type:ux, priority:3
