### ISSUE TITLE
Maps of long ago ranked "Guest Participation Beatmap" not showing up.

### ISSUE THREAD

**Issue by toosu** [ppy/osu-web#8830] opened 2022-04-21 05:32 UTC
It would be better to be able to grant guest privileges after being ranked on beatmap discussion if the system displayed is the one set up in the discussion.

Most maps are not set up because they were not setting in the past.

**Comment by Hiviexd** [comment] 2022-04-21 05:38
duplicate of https://github.com/ppy/osu-web/issues/8243

**Closed** 2022-04-21 05:50 UTC
