### ISSUE TITLE
Verification request disappearing after refreshing the website

### ISSUE THREAD

**Issue by goebeldamian** [ppy/osu-web#7540] opened 2021-04-29 11:34 UTC
While scrolling through the beatmaps section on the website, sometimes I got a pop-up with a verification request. Pop-up disappears after refreshing the website and I am able to scroll freely without providing the verification code.

**Comment by peppy** [comment] 2021-05-04 04:20
Seems very weird and worth investigation.

**Comment by nanaya** [comment] 2021-09-01 05:26
Looks like a duplicate of #7295.

**Comment by peppy** [comment] 2021-09-01 05:33
Basically, the OP here must have triggered an action like favouriting a beatmap, which caused the verification popup. May have been an accidental click. Scrolling alone should not encounter this issue.

**Closed by peppy** 2021-09-01 05:33 UTC
Labels: area:beatmap-listing, type:ux, priority:1
