### ISSUE TITLE
Add basic markdown in v2

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2046] opened 2017-12-20 06:51 UTC
Would be nice to have some of the basics such as bold, italics, underlines and lists just to make things easier to read when needed. Don't need any of the other features, just those is more than enough for v2.

**Comment by peppy** [comment] 2017-12-20 06:51
If anything, this will arrive in the form of markdown, not bbcode.

**Comment by shortthu** [comment] 2017-12-20 08:12
so this would be a duplicate of #451 lol

**Closed** 2017-12-20 08:12 UTC
Labels: feature, modding discussions
