### ISSUE TITLE
User Profile menu suggestion

### ISSUE THREAD

**Issue by tomdenty1** [ppy/osu-web#3369] opened 2018-06-18 19:23 UTC
would it not be better for users to be shown this box while hovering over it, and to be took directly to the users profile when clicked?

Currently clicking your profile pic opens the menu, while hovering does nothing

![image](https://user-images.githubusercontent.com/36710174/41557384-63e10e6a-7335-11e8-8a53-05398b4ba2e0.png)

**Comment by Lyawi** [comment] 2018-06-18 19:44
For the first time that's what I thought it would be. But I figured out fast

(I agree with this tbh)

**Comment by Joehuu** [comment] 2018-06-18 20:00
Duplicate of #2915.

**Comment by notbakaneko** [comment] 2018-06-19 03:35
see #2915

**Closed by notbakaneko** 2018-06-19 03:35 UTC
