### ISSUE TITLE
Mapping subscribers button does not react to change

### ISSUE THREAD

**Issue by jacksonisiah** [ppy/osu-web#7068] opened 2021-01-14 16:43 UTC
Found this when I clicked subscribe by accident, just felt odd & unintentional. 

![the issue](https://b.catgirlsare.sexy/6-wkcmHH.gif)

**Comment by peppy** [comment] 2021-01-15 02:04
Duplicate of https://github.com/ppy/osu-web/issues/7034

**Closed by peppy** 2021-01-15 02:04 UTC
