### ISSUE TITLE
New web breaks compressed urls when saving

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3010] opened 2018-04-14 12:25 UTC
The second hyperlink was compressed on the old web. 
When I saved it on the new web, it broke because it took the ... and not the actual url.

![screen shot 2018-04-14 at 8 22 14 pm](https://user-images.githubusercontent.com/30382015/38768168-f273e4e6-4021-11e8-9336-e9f1133de397.png)

**Comment by dorothy3242** [comment] 2018-04-14 16:47
Duplicate of https://github.com/ppy/osu-web/issues/2930

**Closed** 2018-04-15 04:53 UTC
