### ISSUE TITLE
lazer.ppy.sh show plays much further back than 24hr

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu-web#10565] opened 2023-09-18 10:53 UTC
<img width="982" alt="Skärmavbild 2023-09-18 kl  12 53 18" src="https://github.com/ppy/osu-web/assets/81715029/a4798c2b-bac9-4eb3-a2bd-1ffc88647ad1">

**Comment by peppy** [comment] 2023-09-18 13:09
This is expected behaviour.

**Comment by cl8n** [comment] 2023-09-18 17:54
re-opening because it does say "24h" in that header... should be updated if it's not limited anymore.

**Comment by peppy** [comment] 2023-09-18 18:46
It will be in the future.

The lazer domain is an early acces / beta / ewahtever you want to call it. Thi will be fixed before we combine th eleadrboeards and scoring.

**Closed by peppy** 2023-09-18 18:46 UTC
Labels: area:user-profile, type:cosmetic
