### ISSUE TITLE
"Approved" map section on the website is pointless

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3367] opened 2018-06-18 16:08 UTC
"Ranked & Approved" already includes both all ranked and the old approved mapsets, is there really any point in keeping the "Approved" category when it has not been added to in over 3 years?

**Comment by Joehuu** [comment] 2018-06-18 20:08
Duplicate of the referenced issue.

**Closed** 2018-06-20 02:32 UTC
