### ISSUE TITLE
Can you add the no vid download on the new site?

### ISSUE THREAD

**Issue by Silence38** [ppy/osu-web#2837] opened 2018-03-28 16:43 UTC
my internet is not the best and it takes way longer with the vid downloading too.

**Comment by dorothy3242** [comment] 2018-03-28 16:51
https://github.com/ppy/osu-web/issues/2079   ?
No video download links can also be accessed on the map's information page, unless something else went wrong.

**Comment by peppy** [comment] 2018-03-29 04:38
Duplicate of #2079.

**Closed by peppy** 2018-03-29 04:38 UTC
