### ISSUE TITLE
Nominated Beatmaps show as "Graveyard" on info page

### ISSUE THREAD

**Issue by Feerum** [ppy/osu-web#5608] opened 2020-02-07 17:18 UTC
There are currently some Beatmaps which show "Graveyarded" on the Beatmap-Info page, while they are nominated. 
Nominated Beatmaps should not get graveyarded, at least that was the case in the past. They also still showing as "Pending" on the user page of the beatmap host.

Example Beatmaps: https://osu.ppy.sh/beatmapsets/982271%3C#mania/2055771
https://osu.ppy.sh/beatmapsets/987631#taiko/2066066

Both beatmaps have a 1/2 Nomination status. 

Not sure if this is a bug or if something got changed recently.

**Comment by Em0nky** [comment] 2020-02-07 19:56
It's not just maps that are nominated, it is pending maps as well.
![chrome_2020-02-07_14-55-30](https://user-images.githubusercontent.com/60788724/74061458-0c759a80-49ba-11ea-8f3a-78e1aaab3475.png)
![chrome_2020-02-07_14-55-43](https://user-images.githubusercontent.com/60788724/74061460-0d0e3100-49ba-11ea-92ee-c32d71ce5c6e.png)
![chrome_2020-02-07_14-55-53](https://user-images.githubusercontent.com/60788724/74061461-0d0e3100-49ba-11ea-80e7-e54367f63135.png)

**Comment by cl8n** [comment] 2020-02-07 20:05
the beatmapset has the correct value, but each diff is marked graveyarded in these examples, and now it shows because #5593. here's another where one diff is graveyarded and the others are WIP https://osu.ppy.sh/beatmapsets/1061817

probably bss issue for @peppy

**Comment by peppy** [comment] 2020-02-07 23:51
will fix this on a per beatmap basis for now. it should repair on status change i believe

**Comment by dorothy3242** [comment] 2020-02-09 14:35
If status change refers to updating beatmaps, this is not happening.
https://osu.ppy.sh/beatmapsets/1019398#osu/2133119

The mapper updated this mapset yesterday, and the status of the other difficulties changed to wip, but the top difficulty is still marked as graveyarded.

There's quite a bit of confusion right now due to a lot of pending maps having diffs marked as graveyarded,  would it be possible to make the per diff labels exclusive to sets that are in loved/ranked, or do a full pass to fix the current inconsistencies in pending/wip?

**Comment by peppy** [comment] 2020-02-09 14:42
As above, I will be fixing this.

**Comment by peppy** [comment] 2020-02-09 15:28
This should now be fixed. Could you please confirm and report any remaining issues?

**Comment by Em0nky** [comment] 2020-02-09 20:50
Seems to be fixed, I can't find any maps with incorrect things now.

**Comment by mayymay** [comment] 2022-02-16 04:03
One of my beatmaps unfortunately still has this issue. I've tried various things over the last year and a half to fix it to no avail. It is technically pending (or at least that's what I choose every time I update it) but appears as WIP on the beatmap listing and  both WIP and graveyarded on the actual beatmap page itself.

![image](https://user-images.githubusercontent.com/99781442/154193703-252f12e8-ed52-48a3-9e38-5390f1fe5403.png)
![image](https://user-images.githubusercontent.com/99781442/154193664-cdb26db9-623c-4c5a-940f-8d81ad5e62e5.png)
![image](https://user-images.githubusercontent.com/99781442/154193803-f4494fbf-58e9-4aac-9831-b7e423711f2f.png)

**Comment by peppy** [comment] 2022-02-16 04:53
Could you... please.. link the beatmap..?

**Comment by mayymay** [comment] 2022-02-16 04:55
> Could you... please.. link the beatmap..?

Yeah sorry I completely forgot 
https://osu.ppy.sh/beatmapsets/1238584#osu/2577480

**Comment by peppy** [comment] 2022-02-16 05:27
I've fixed your map. Will investigate how this could have happened and apply a fix if necessary.

**Comment by cl8n** [comment] 2022-02-19 04:37
thanks to the status search options having different behavior ("status=" checks for beatmap status, "Categories" checks for beatmapset status), all maps with weird statuses can be found:

https://osu.ppy.sh/beatmapsets?q=status%3Dwip&s=graveyard
https://osu.ppy.sh/beatmapsets?q=status%3Dgraveyard&s=pending

some of these have been updated recently, so I think this issue should stay open.

I checked all the status combinations and the only other cases of mixed status are intentional; Loved TAG4 diffs are in Ranked mapsets, and lots of Pending/WIP/Graveyard diffs are in Loved mapsets

**Comment by peppy** [comment] 2022-02-21 15:48
Just to confirm: I can only see two beatmaps in total on the linked search pages. Are you seeing more somehow?

**Comment by nanaya** [comment] 2022-02-21 15:50
With the recent split of wip/pending there's another search option to be checked

https://osu.ppy.sh/beatmapsets?q=status%3Dgraveyard&s=wip

**Comment by peppy** [comment] 2022-02-24 07:54
Reopening this while I investigate a second time.

For what it's worth, I *did* apply a second fix for this, but that was within the last 15 days. In the search results I haven't seen any cases of it happening since then, but I will go and fix the other cases that have come up at very least.

**Comment by peppy** [comment] 2022-02-25 06:03
I've confirmed that all the incorrect matches occurred before the fix was rolled out. I've re-run consistency checks and fixed all the incorrect mappings. Will close this issue again, but as always feel free to comment if it comes up again in the future, there may be some other case I've missed.

**Closed by peppy** 2022-02-25 06:03 UTC
