### ISSUE TITLE
Modding Watchlist table breaks the width on mobile

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2725] opened 2018-03-18 09:05 UTC
![](https://puu.sh/zK9GQ/2fc35f282c.png)

**Comment by MegaApplePi** [comment] 2018-03-27 04:59
Duplicate of #1750

**Comment by peppy** [comment] 2018-03-29 07:14
Closing as duplicate of #1750.

**Closed by peppy** 2018-03-29 07:14 UTC
Labels: bug, mobile
