### ISSUE TITLE
Implement "rank change" indicator for rankings

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu-web#10089] opened 2023-04-07 16:12 UTC
So the idea is coming from IMDb where you can see a movie placing change in a certain amount of time: 

![image](https://user-images.githubusercontent.com/86934170/230640254-95f31fe6-0963-4878-90f8-78f793b69921.png)

You can grab the delta of ranking change for 30 days from every profile and display it near the actual ranking like this:

![Untitled](https://user-images.githubusercontent.com/86934170/230641259-de82611f-cae3-4f41-ac87-0483fa6075c4.png)

**Comment by peppy** [comment] 2023-08-22 06:40
This used to be a thing, but was never re-implemented with the new site.

Could probably add back without much effort. I think we already have all the data in the `osu_user_rank_history` table for up to 90 days.

**Comment by cl8n** [comment] 2023-09-10 15:54
duplicate of #7391

**Closed by cl8n** 2023-09-10 15:54 UTC
Labels: area:rankings, priority:2
