### ISSUE TITLE
Enable getting profile "me!" data via API

### ISSUE THREAD

**Issue by c-sig** [ppy/osu-web#5630] opened 2020-02-14 07:04 UTC
It would be kinda neat to get the data from different "me!" sections from other profiles so that we can probably use the data to make more neat stuff i.e. Tracking of Beatmap Nominator userpages for easy viewing rather than going to each individual one. It's also cool to see who's available for a bubble whenever they say "Active" or something in their userpages.

**Comment by venix12** [comment] 2020-02-14 07:11
isn't it a thing in api v2?

**Comment by notbakaneko** [comment] 2020-02-14 08:19
It's not exposed to anything outside of the game client yet

**Comment by venix12** [comment] 2020-02-14 08:48
i believe i have seen it in ``/me`` response when I was doing an OAuth system, thought it was kinda the same for ``/user``

**Comment by cl8n** [comment] 2020-02-14 08:51
it is the same, but `/users` is only available for lazer right now

**Comment by notbakaneko** [comment] 2020-02-21 09:21
duplicate of #4798

**Closed by notbakaneko** 2020-02-21 09:21 UTC
Labels: api
