### ISSUE TITLE
Suggestion: Use old site thumbnails for left side of beatmapset card

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#7467] opened 2021-04-11 20:21 UTC
Related to #7456 

Instead of adjusting card cropping or inventing a new algorithm I'm proposing using thumbnails from old site (https://b.ppy.sh/thumb/%beatmap_id%l.jpg) since they're still being generated. In my opinion this might be a good transitional change before you come up with a better solution.

Examples
**Before**:
![image](https://user-images.githubusercontent.com/8269193/114319965-60c75d80-9b1c-11eb-8608-ac72466566e3.png)

**After**:
![image](https://user-images.githubusercontent.com/8269193/114319951-53aa6e80-9b1c-11eb-827d-226cfc9e43a9.png)

**Comment by peppy** [comment] 2021-04-12 00:55
Thanks for the suggestion.

We are already looking at design changes including something along these lines internally.l

**Comment by peppy** [comment] 2021-04-12 00:56
Not sure why this issue was opened (it's a duplicate of the "related" issue).

**Closed by peppy** 2021-04-12 00:56 UTC
