### ISSUE TITLE
Resolving discussions should be disabled when a map is in qualified.

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2128] opened 2017-12-28 15:41 UTC
Mappers can resolve issues the moment they are posted on a qualified map to avoid a dq. Pending discussions are far more likely to be spotted by other modders than resolved ones. Discussions posted after qualification should be left open in order for other community members to provide further feedback on whether or not it's a dq worthy issue.

Once a set is ranked or disqualified, resolving discussions would be enabled again.

**Comment by Mirruuu** [comment] 2017-12-28 15:49
What if the issue isn't worth disqualifying for/the mapper provides sufficient enough reasoning/it's a non-issue to begin with? They can't resolve it then.

**Comment by Xinnoh** [comment] 2017-12-28 15:51
leave it open and just close afterwards, it's more important to leave all issues up to be seen than to close and hide them all. If it's not worth fixing then just resolve them after rank/dq

**Comment by Mirruuu** [comment] 2017-12-28 15:52
If all issues get auto-resolved or something after rank then fine by me.

**Comment by maridius98** [comment] 2018-03-07 13:05
Other than bumping, I suggest that the initial poster of a concern be able to close it together with QAT. Also shitposting and straight up insults posted as issues should get users silenced and the post removed. 

I feel like some kind of a thread for shitposts, congratulations and player feedback should be made after qualification.

**Comment by Xinnoh** [comment] 2018-03-07 13:28
"General All difficulties" is generally used as the shitpost thread, but that's also where the majority of the discussion is happening so it gets confusing. 
[Example](https://osu.ppy.sh/beatmapsets/736560/discussion/-/generalAll) of the thread becoming wayyyyy too disorganised due to how v2 works

**Closed** 2018-10-15 07:44 UTC
Labels: modding discussions, proposal
