### ISSUE TITLE
Add warning about .jpg conversion for avatar upload

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2884] opened 2018-04-02 04:39 UTC
Since all uploaded avatars via the new website are forcibly changed to .jpg images, this should be mentioned somewhere here instead of it catching a user trying to use a partially transparent .png avatar off-guard.

**Comment by MegaApplePi** [comment] 2018-04-02 04:40
Duplicate of #1579

**Comment by dorothy3242** [comment] 2018-04-02 04:41
Updated to reflect where the issues do not overlap.

**Comment by peppy** [comment] 2018-04-02 13:13
Conversion only happens when avatar is larger than the specified dimensions.

**Comment by Xinnoh** [comment] 2018-04-02 13:31
should also mention the maximum size for uploads

**Comment by peppy** [comment] 2018-04-02 16:30
Related: ppy/osu-web#2894

**Comment by cl8n** [comment] 2020-06-08 08:53
it doesn't seem necessary after #4589 (fixed what peppy linked above)

**Comment by peppy** [comment] 2020-06-12 05:42
Sounds fair.

**Closed by peppy** 2020-06-12 05:42 UTC
Labels: type:ux
