### ISSUE TITLE
Give Moderators the option to edit beatmap discussion replies

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8776] opened 2022-04-05 17:24 UTC
Beatmap discussions are the only place were moderators can not edit the content but rather have to remove the entire comment, which can lead to issues like qualified maps with 4/5 hypes and deleting big sections with valid points just because part of it is inproper.

Apparently web-admins already have the option to edit this, no clue why moderators.

**Comment by NoffyNoffeh** [comment] 2022-04-05 17:27
Duplicate of https://github.com/ppy/osu-web/issues/3642 

which already sounds like having deletion be the only option is the future direction for moderation.

**Comment by Pachiru** [comment] 2022-04-05 17:27
Also using this thread to eventually allow moderators to have an edit history to make sure there is no abuse?

**Comment by peppy** [comment] 2022-04-06 02:35
I think the conversation here explains the scope creep of this, and why it doesn't exist yet.

Nice to have, but also quite time consuming to implement (especially if applied to all places edit currently exists).

**Comment by RockRoller01** [comment] 2022-04-06 02:52
the history of edits is a completly seperate thing, this issue was only about adding the edit option, which GMT/NAT have in all other places and for some reason only web admins have on discussion posts

**Comment by peppy** [comment] 2022-04-06 03:15
To make myself clearer: I'd sooner remove the ability for moderators to edit the other areas than add one more. I don't think we want to be editing user content like that.

**Closed** 2022-04-06 13:53 UTC
Labels: proposal, area:beatmap-discussions
