### ISSUE TITLE
[Old-Feature] Missing osu!supporter expiration date check in new web

### ISSUE THREAD

**Issue by RaikireHiuduo** [ppy/osu-web#2027] opened 2017-12-19 07:21 UTC
Old supporter page: https://osu.ppy.sh/p/support
New supporter page: https://osu.ppy.sh/home/support

Suppose I have an active osu!supporter, **where** do I refer to the **expiration date for the osu!supporter** in the **new web**?

In the old web, I can just visit the old supporter page and the expiration date is shown at the top.
For the new web, I have no idea where to find it.

Issue is related to wiki page for osu!supporter: https://github.com/ppy/osu-wiki/pull/706

**Comment by peppy** [comment] 2018-04-04 06:27
Closing as duplicate of #2782.

**Closed by peppy** 2018-04-04 06:27 UTC
Labels: feature, store
