### ISSUE TITLE
Comment upvote counter goes out of bounds when the number of upvotes reaches 3 digits

### ISSUE THREAD

**Issue by tuudug** [ppy/osu-web#9767] opened 2023-01-19 11:50 UTC
Could be seen on the comments of [this map](https://osu.ppy.sh/beatmapsets/1421463#taiko/2927854)

![image](https://user-images.githubusercontent.com/16380030/213435132-e2f25af1-eb44-4b40-96b9-f64e52877983.png)

**Comment by nanaya** [comment] 2023-01-19 11:52
duplicate of #7379

**Closed by nanaya** 2023-01-19 11:52 UTC
