### ISSUE TITLE
Hype counter showing null/null instead of 0/0

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu-web#6926] opened 2020-12-02 19:22 UTC
As of recently it has come to my attention that the hype counter frequently will show null/null instead of the usual 0/0
Heres a screencap of it:
![image](https://user-images.githubusercontent.com/33634370/100920771-e2a6da80-34db-11eb-82a4-5259244878eb.png)

**Comment by venix12** [comment] 2020-12-02 20:12
duplicate of #6915, this was meant to be fixed by #6919 though 🤔

**Comment by Eeveelution** [comment] 2020-12-02 20:13
seems to still not work though... not sure why

**Comment by bdach** [comment] 2020-12-02 20:30
The change in question might not have been deployed yet, seeing it's not in [yesterday's release changelog](https://osu.ppy.sh/home/changelog/web/2020.1201.0).

**Comment by Joehuu** [comment] 2020-12-02 20:34
Closing as resolved, just need to wait for next deploy.

**Closed by Joehuu** 2020-12-02 20:34 UTC

**Comment by Eeveelution** [comment] 2020-12-02 20:50
aaaaaa, didnt know that was a thing. sorry
