### ISSUE TITLE
All user profile elements should be collapse-able

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-web#5515] opened 2020-01-19 19:53 UTC
On your own user page, you can collapse a portion of your ranking statistics with a [toggle-able switch on the right hand side of the screen.](https://i.imgur.com/SSqanPj.png)

However all other user profile elements (besides profile cover and profile page) have no such functionality. They do however have a [convenient empty space where there could be a similar toggle switch.](https://i.imgur.com/Lj2rba6.png)

Allowing the rest of the user page to be collapse-able would help with the problem of user pages being too large and cluttered (taking approximately 3 seconds to scroll through the entire user page) and hide some of the massive user profile elements such as the medals section.

**Comment by TPGPL** [comment] 2020-01-19 19:59
possibly duplicate of #3630

**Comment by nl-tatatat** [comment] 2020-01-19 20:15
hmm, I agree. but I think mine might present more information.

**Comment by peppy** [comment] 2020-01-20 03:47
Going to close this as a duplicate. We are working to reduce the height of sections like medals in upcoming design refactors, which should help with the issues you're pointing out (similar attention is also given to the user page).

**Closed by peppy** 2020-01-20 03:47 UTC
