### ISSUE TITLE
Sub-notifications have no icon

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6042] opened 2020-05-23 02:35 UTC
![example](https://user-images.githubusercontent.com/13962537/82719879-dee20200-9cc7-11ea-8bc5-1813a5b60291.png)

**Comment by Joehuu** [comment] 2020-05-23 02:41
Duplicate of https://github.com/ppy/osu-web/issues/5905

**Comment by notbakaneko** [comment] 2020-05-25 09:15
these should be split out as mentioned in #5905

**Closed by notbakaneko** 2020-05-25 09:15 UTC
