### ISSUE TITLE
allow multiple creators of difficulty assign to beatmaps

### ISSUE THREAD

**Issue by mousesalt** [ppy/osu-web#8842] opened 2022-04-23 18:24 UTC
currently only one creator of difficulty can be added to a map. 
not sure if this duplicate

![Screenshot_2022-04-24-01-14-35-024_com.android.chrome.jpg](https://user-images.githubusercontent.com/39128490/164934743-0a777a79-dd42-4bc4-92da-11441f5028bb.jpg)

**Comment by apollo-dw** [comment] 2022-04-23 18:25
duplicate of https://github.com/ppy/osu-web/issues/7602

**Closed by apollo-dw** 2022-04-23 18:25 UTC
