### ISSUE TITLE
+1 indicator border going outside of comment element when votes are greater than 100

### ISSUE THREAD

**Issue by SquishyMan1** [ppy/osu-web#9680] opened 2022-12-27 18:49 UTC
When a comment gets above 100 votes, the border of the button will end up exceeding the comments area. The pictures below show this problem in greater detail. This problem occurs in both Firefox and Chrome in my experience. The website should have a way to either shrink the text down over 100 votes, make the button border smaller, or a combination of both. 

<img width="1006" alt="Screenshot 2022-12-27 at 10 45 02 AM" src="https://user-images.githubusercontent.com/67621489/209709276-470b852f-1e8f-4218-af45-16a974df7973.png">
<img width="1003" alt="Screenshot 2022-12-27 at 10 47 37 AM" src="https://user-images.githubusercontent.com/67621489/209709518-894e4e33-2131-42fa-aa5f-8d42d8d50e53.png">
<img width="65" alt="Screenshot 2022-12-27 at 10 48 04 AM" src="https://user-images.githubusercontent.com/67621489/209709551-b1ce9c00-ad53-42b3-b93d-c6e023f32624.png">

**Comment by tybug** [comment] 2022-12-27 18:51
duplicate of #7379

**Closed** 2022-12-27 18:52 UTC
