### ISSUE TITLE
Join date on the forum is displayed at the very end of the title/flag field instead of directly under the user's flag.

### ISSUE THREAD

**Issue by Galkaan** [ppy/osu-web#2785] opened 2018-03-23 16:21 UTC
![screenshot-osu ppy sh 2018 03 23 17-18-02](https://user-images.githubusercontent.com/21173359/37840756-3bdef5e6-2ebe-11e8-842f-2cbac6e15c87.png)

Ends up looking somewhat random/unaesthetic for longer forum posts. Link to an example thread where the issue appears: https://osu.ppy.sh/community/forums/topics/685583

**Comment by nanaya** [comment] 2018-03-23 16:24
Duplicate of #435 and probably will be fixed on next design.

**Closed by nanaya** 2018-03-23 16:24 UTC
