### ISSUE TITLE
Language list not showing as whole

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#2085] opened 2017-12-23 14:29 UTC
at the moment Chinese is pretty hard to choose

![chrome_2017-12-23_15-28-52](https://user-images.githubusercontent.com/32525896/34320261-038880a4-e7f6-11e7-8f63-7db8b23464e5.png)

**Comment by peppy** [comment] 2017-12-23 14:29
We are well aware. A new design is in the works.

**Comment by nekodex** [comment] 2017-12-23 14:31
Duplicate of #2070

**Closed by nekodex** 2017-12-23 14:31 UTC
