### ISSUE TITLE
Manual profile picture cropping

### ISSUE THREAD

**Issue by creatorl2** [ppy/osu-web#8569] opened 2022-01-31 00:42 UTC
When you upload an image to use as your profile picture, currently what happens is that it just uses the entire image as your profile picture or crops it so it fits a square resolution. This leads to a minor inconvenience in which you have to use some external image editing program such as paint.net to crop the image to what you want it to be. An example of this is say, when you want the face of an anime girl to be your profile picture but the source image is a body shot. You have to open paint.net and crop it to just the face because if you upload the body shot as your profile picture it'll upload the entire image.

I think a good solution to this is something like how Twitter lets you crop images to use them as a profile picture, letting you zoom in on the picture and select an area of the image you want to use before it updates your profile picture.

**Comment by peppy** [comment] 2022-01-31 02:44
Duplicate of https://github.com/ppy/osu-web/issues/8353.

**Closed by peppy** 2022-01-31 02:44 UTC
