### ISSUE TITLE
Negative rank count

### ISSUE THREAD

**Issue by chipposu** [ppy/osu-web#7152] opened 2021-02-02 17:41 UTC
![image](https://user-images.githubusercontent.com/78438569/106640387-e0b1d400-657d-11eb-89ba-817729e5c14d.png)
[https://osu.ppy.sh/users/10690090](url)

**Comment by troke12** [comment] 2021-02-07 15:11
I'm already see this from other player, that he got the minus from the map who got qualified and wait after ranked, so the score you have in qualified map will be removed (not count)

**Comment by nanaya** [comment] 2021-02-08 04:26
@peppy, which stats on `osu_user_stats*` are actually updated for plays on qualified maps? It looks like the SS/S/A/etc rank counts aren't updated?

**Comment by Magnus-Cosmos** [comment] 2021-08-03 06:29
When a qualified map gets ranked the scores are deleted: https://github.com/ppy/osu-web/blob/2a821dc8aad5ee8f85f72cec6db15a971df7252a/app/Jobs/RemoveBeatmapsetBestScores.php#L67-L73
Whenever a score is deleted it decrements the corresponding rank: https://github.com/ppy/osu-web/blob/2a821dc8aad5ee8f85f72cec6db15a971df7252a/app/Models/Score/Best/Model.php#L339-L360
The issue is when a player has more than one score on a qualified beatmap (by using different mods). When the plays are set, only the player's best/top score counts towards their rank stats, however when they are deleted, every score is subtracted from rank stats. This causes rank stats to decrease more than they should, allowing for things like negative SS count)

**Comment by peppy** [comment] 2021-08-03 07:04
Nice deduction work there. Going to unassign this as it seems like an osu-web issue which can better be addressed by others.

Once it's fixed I'll do a full reprocess of rank counts.

**Closed** 2021-08-13 12:39 UTC
Labels: area:scoring, priority:0
