### ISSUE TITLE
make qualified/ranked dates show in beatmap listings

### ISSUE THREAD

**Issue by elucidium** [ppy/osu-web#3115] opened 2018-05-01 02:17 UTC
having dates show is actually quite an underrated feature and would be nice on the new web design

![firefox_2018-04-30_22-12-05](https://user-images.githubusercontent.com/8270776/39458618-f64258c4-4cc3-11e8-873f-f5710b502ace.png)

![firefox_2018-04-30_22-12-47](https://user-images.githubusercontent.com/8270776/39458620-f7a0a6c6-4cc3-11e8-9c42-b34b02d2c45d.png)

showing date of last update for pending maps might also be something to consider, although i guess that's less important than displaying them for maps in the ranked section

**Comment by peppy** [comment] 2018-05-02 03:48
Closing as duplicate of #3055.

**Closed by peppy** 2018-05-02 03:48 UTC
