### ISSUE TITLE
Visual bug of new design

### ISSUE THREAD

**Issue by Vitas2222** [ppy/osu-web#7459] opened 2021-04-09 14:53 UTC
Pretty simple report:
You can't see star rate and names of difficulties in osu! profile on the last graveyard map.
![Screenshot](https://user-images.githubusercontent.com/82224438/114198939-4dc25b00-996d-11eb-8a72-720e5e9015c8.png)

**Comment by NoffyNoffeh** [comment] 2021-04-09 14:56
Duplicate of https://github.com/ppy/osu-web/issues/7450

**Closed** 2021-04-09 14:57 UTC
