### ISSUE TITLE
Text formatting options missing/misleading 

### ISSUE THREAD

**Issue by Niftys** [ppy/osu-web#3707] opened 2018-09-25 06:53 UTC
Arguably the most useful formatting shortcut, centre, is missing from the new site's text editor. the spoiler box shortcut is there, but when you use it, it creates a box, not a spoiler box. Also, the all too important spoiler shortcut isn't there either. The others that are left out are practically useless, so that's aight, but the centre shortcut missing has been getting on my nerves.

**Comment by Celektus** [comment] 2018-09-26 06:13
What's the difference between  
```
[box=][/box] 
``` with no text in it and the normal spoilerbox? 
```
[spoilerbox][/spoilerbox] 
```

**Comment by Niftys** [comment] 2018-09-26 06:18
https://sv.s-ul.eu/lViHG5xX

One says SPOILER and the other doesn't.

I mean this was opened more for the centre shortcut to be added to new site.

**Comment by Celektus** [comment] 2018-09-26 06:19
Yea I agree centre REALLY should be there I'm using it pretty much constantly

**Comment by TPGPL** [comment] 2019-09-27 15:45
duplicate of #2357?

**Comment by nanaya** [comment] 2023-03-23 04:50
(duplicate as mentioned above)

**Closed** 2023-03-23 04:49 UTC
Labels: area:forum, type:ux
