### ISSUE TITLE
Updating metadata of a beatmap causes mods to disappear and the map to appear as deleted

### ISSUE THREAD

**Issue by Commie-Husky** [ppy/osu-web#1890] opened 2017-12-04 08:57 UTC
![image](https://tess.s-ul.eu/vHC0ZrJL)
https://osu.ppy.sh/beatmapsets/684013/discussion#/21128 this is the beatmap this happened on

**Comment by peppy** [comment] 2017-12-04 09:02
Did the user manually edit the .osu file?

**Comment by Commie-Husky** [comment] 2017-12-04 09:06
Not as far as I'm aware, they were discussing manually setting the id to the old one in the .osu to fix this issue so i assume not

**Comment by peppy** [comment] 2017-12-04 09:07
I've fixed this locally, but more information is required on how this happened in order to figure out a resolution. .osu files contain a BeatmapID which is used to retain information like this when their metadata is changed. The only logical way I can see this happening is if:

- The user submitted with the difficulty completely deeleted, then submitted again with it added back.
- The user manually updated the .osu file and removed this information.

Would be interested to know the process involved in the updating of the map.

**Comment by Commie-Husky** [comment] 2017-12-04 09:22
Sinnoh and I have asked the mapset holder to post in here so he probably will as soon as he gets on.

**Comment by MrMenda** [comment] 2017-12-04 11:57
What happened was that I asked a third person to hitsound the map for me and I uploaded it with the difficulty called HS, which had exactly the same data as the current top difficulty. 

When I accidentally uploaded both maps, HS difficulty got all of the suggestions/problems the modders (xLolicore- and Kisses) and Masterpiece difficulty lost them all. After deleting HS from the set and reuploading, all of the mods got lost.

**Comment by Celektus** [comment] 2017-12-04 15:27
it should be mentioned that a tool by the user Sieg was used to copy the hitsounds: [**another hitsound copier**](https://osu.ppy.sh/forum/p/5427690)

also I was the Hitsounder and the HS diff in question wasn't exactly the same as the original top diff, in other words it was treated as a different diff from the top diff

**Comment by peppy** [comment] 2017-12-04 15:57
Submitting two difficulties with the same ID would definitely break things. Thanks for the explantion. I'd advise not using external tools as this kind of thing can happen.

**Comment by Okorin** [comment] 2017-12-04 16:12
what if people use this to force flush discussions?

**Comment by Celektus** [comment] 2017-12-04 16:26
There's actually a chance that it's caused by something else or this tool specifically since I've personally used different a HS copier for my own v2 maps without breaking anything. Also do single diffs have the same ID or does this apply to the whole set or does the ID get copied even if the name of the diff was changed? I guess it just happens when it confuses IDs as suggested by Menda saying:

> HS difficulty got all of the suggestions/problems the modders (xLolicore- and Kisses) and Masterpiece difficulty lost them all.

**Comment by peppy** [comment] 2017-12-04 16:40
You submitted two difficulties with the same UD. The server updated the first and published the second as a new map because it couldn’t reuse the same ID.

Then when you deleted the first you lost the attached comments and everything else.

If you’re going to manually edit files, please remove all IDs from newly created difficulties before running osu.

**Comment by Xinnoh** [comment] 2017-12-07 01:09
Renaming a diff also resets mods, people do this all the time. Un-intentional resets will happen.

**Comment by peppy** [comment] 2017-12-07 04:29
No it doesn't.

**Comment by peppy** [comment] 2017-12-22 06:25
Closing as resolved. Will be able to see deleted maps in #1814 as a bonus.

Contact me at pe@ppy.sh if you break your map and I'll manually fix it.

**Closed by peppy** 2017-12-22 06:25 UTC
Labels: modding discussions
