### ISSUE TITLE
Number display on beatmap cards is not localised

### ISSUE THREAD

**Issue by EddieYang1222** [ppy/osu-web#7457] opened 2021-04-09 14:22 UTC
A certain number of players may have difficulties in understanding what "k" and "m" refer to in the numbers shown on the cards, so for different languages available for translation, they should be translated.

**Comment by peppy** [comment] 2021-04-09 14:24
The hover elements are going to stay as hover elements. Please hover to view the hover content. This is intentional. Please use a browser extension if you can't handle this.

I'll edit this issue to cover numeric localisation.

**Comment by nanaya** [comment] 2021-04-09 14:24
The second part is duplicate of #4192.

**Closed** 2021-04-09 14:24 UTC
Labels: area:beatmap-listing, type:localisation

**Comment by EddieYang1222** [comment] 2021-04-09 14:27
Thank you. Would you mind elaborating more on the browser extension to use for displaying hover contents?

**Comment by iptq** [comment] 2021-04-09 14:27
> The hover elements are going to stay as hover elements. Please hover to view the hover content. This is intentional.

What was the reasoning behind this choice? Many people have expressed that they find it more useful to see the numbers directly.

If you'd like, I can open a new issue for this

**Comment by nanaya** [comment] 2021-04-09 14:30
There are alternative card designs but it's not yet implemented.

For showing the numbers all the time
```css
.beatmapset-panel { --stats-opacity: 1 !important; }
```

**Comment by EddieYang1222** [comment] 2021-04-09 14:31
Thank you!
