### ISSUE TITLE
Bullet points look wrong in some instances

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#29] opened 2015-09-03 00:27 UTC
Likely bbcode parsing failure: http://jizz.ppy.sh/forum/t/259747?start=3508242#forum-post-3508242

![](http://puu.sh/jXZEu/6d7ae40601.png)

**[Bounty](https://goo.gl/nFdoyI) offered**: 4

**Comment by tewki** [comment] 2015-09-03 02:12
For anyone who wanna fix as I don't have my normal environment, that caused by HTMLPurifier's strict parsing because of the tags that is in it (any tag) as it interprets it as only having the *ol* tag with no *li* tag surrounding it which is going against the strict parsing,
Thus it pushes the end stack to the beginning of that tag (This case *em*) and wraps the content with *li*.

So it's either to try to make HTMLPurifier ignore it or surround the content if has none with a *li* or the bbcode needed for it.

**Comment by kcaze** [comment] 2015-09-04 03:15
The exact issue we're seeing is http://stackoverflow.com/questions/29433364/htmlpurifier-prepending-extra-list-item-to-all-lists.

There are extra `<br/>`'s being added to the list because we're appending a `<br/>` to all `\n` characters. The easiest fix for this is to append `<p></p>` instead of `<br/>` elements. Here's a screenshot where `<p></p>` is inserted instead of `<br/>`:
http://up.ppy.sh/files/screenshot2015-09-03at8.13.44pm.png

**Comment by peppy** [comment] 2015-09-08 10:38
Another case:

![](http://puu.sh/k43Zv/d0ebe764b5.png)

http://jizz.ppy.sh/forum/t/364888?start=4490864#forum-post-4490864

**Comment by VeilStar** [comment] 2015-10-20 08:58
Posting this as it might be useful.

If you open the "List of Confirmed Threads by Category" in this thread https://jizz.ppy.sh/forum/t/338103. It's a spaghetti mess while it's fine on the old forum. https://osu.ppy.sh/forum/t/338103. There is nothing wrong with the way the bbcode is used in that post as far as I'm aware.

Also leaving these screenshots here as examples of when these issues happen.

![01](https://cloud.githubusercontent.com/assets/14024130/10602578/7f2b7fc2-7719-11e5-8634-c3c6d4625804.jpg)

![02](https://cloud.githubusercontent.com/assets/14024130/10602580/7f2dd6d2-7719-11e5-8993-f5a3a943694f.jpg)

![03](https://cloud.githubusercontent.com/assets/14024130/10602579/7f2d22e6-7719-11e5-8635-20efa8a94f77.jpg)

**Comment by nanaya** [comment] 2015-10-20 09:12
no, it isn't valid. You're not supposed to put runaway content (item without preceding `[*]`) in a list. The reason it seemed to work is because that's the way html works: it tries its best making sense out of whatever crap it's gotten. Also known as [tag soup](https://en.wikipedia.org/wiki/Tag_soup).

```
[list]Some runaway content
[*]List 1
[*]List 2
[/list]
```

Make it like this

```
Not a runaway content
[list]
[*]List 1
[*]List 2
[/list]
```

**Closed** 2016-05-06 11:11 UTC
Labels: 0-100, bounty, bug
