### ISSUE TITLE
External links can be clickable and open in Beatmap comments

### ISSUE THREAD

**Issue by AyeAries** [ppy/osu-web#3835] opened 2018-10-25 12:43 UTC
Hopefully for this one to make less hassle to do copy/paste the link.

https://i.imgur.com/LbtMxgg.png

**Comment by Joehuu** [comment] 2018-10-25 13:28
Duplicate of #3744.

**Comment by nanaya** [comment] 2018-10-31 03:11
Indeed a duplicate.

**Closed by nanaya** 2018-10-31 03:11 UTC
