### ISSUE TITLE
Recaptcha not appearing when trying to log in

### ISSUE THREAD

**Issue by Kwantis1** [ppy/osu-web#11515] opened 2024-09-28 16:17 UTC
I recently got a new laptop but cannot log into osu! online since the cloud flare recaptcha does not appear. I tried multiple different web browsers and switched wifi networks but nothing seems to be working. The recaptcha appears on my pc and iphone when I logged out in back in, but for some reason does not appear on my laptop. I did a fresh install of windows to see if there was any software from the manufacturer blocking the osu website from displaying the recaptcha but that still did not work. If you could help me address this problem that would be great.
![image](https://github.com/user-attachments/assets/ba29c618-ca50-437a-ac01-326891f87a8d)

**Comment by nanaya** [comment] 2024-09-28 16:22
check if your system clock is correct (including the timezone).

looks like a Duplicate of #11289

**Closed by nanaya** 2024-09-28 16:22 UTC

**Comment by Kwantis1** [comment] 2024-09-28 16:37
Thank you so much you are a lifesaver
