### ISSUE TITLE
Incorrect date on news posts

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#5112] opened 2019-10-15 06:22 UTC
The dashboard shows the incorrect date. At first, I thought it was because of the timezones, but when you open the post, the correct date is shown...
![](https://imgur.com/yOm3Ipt.png)
![](https://imgur.com/otrfLPj.png)

**Comment by Joehuu** [comment] 2019-10-15 06:27
Duplicate of https://github.com/ppy/osu-web/issues/3936

**Closed** 2019-10-15 06:32 UTC
