### ISSUE TITLE
Highlight recent top pp plays on user's profile

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#7426] opened 2021-04-06 15:40 UTC
Best Performance section has a bunch of top pp plays, but you need to parse through them to see which ones are recent. It would great if recent ones were highlighted to make them stand out.

**Comment by peppy** [comment] 2021-04-07 12:12
@arflyte any ideas for this one? maybe an outline around the score or just highlighting the relative timestamp on them?

**Comment by arflyte** [comment] 2021-04-08 06:26
Hmm, yeah. I can think of something to highlight this.

**Comment by nanaya** [comment] 2021-09-21 04:38
Duplicate of #2781.

**Closed by nanaya** 2021-09-21 04:38 UTC
Labels: area:user-profile, priority:3
