### ISSUE TITLE
Basic urls should be correctly hyperlinked

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#3792] opened 2018-10-12 06:30 UTC
Currently you can use markdown formatting of URLs `[https://...]()` and they will hyperlink, but plain `https://...` links do not. They should.

**Comment by TPGPL** [comment] 2018-10-12 06:42
Related to #3744 i think

**Comment by nanaya** [comment] 2018-10-15 06:01
Duplicate of #3744.

**Closed by nanaya** 2018-10-15 06:01 UTC
Labels: comments
