### ISSUE TITLE
Max combo is null in API for taiko beatmaps

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-web#5537] opened 2020-01-23 13:40 UTC
How to reproduce: request any taiko beatmap from API.

How to fix: set max combo to circle count for taiko.

**Comment by peppy** [comment] 2020-01-23 13:41
Please include details, such as which endpoint, which beatmap, etc.

**Comment by pavlukivan** [comment] 2020-01-23 13:43
Any endpoint which returns beatmap info. Example: `https://osu.ppy.sh/api/get_beatmaps?k=<key>&s=28705&m=1`

**Comment by peppy** [comment] 2020-01-23 13:50
Closing as duplicate of https://github.com/ppy/osu-api/issues/266

**Closed by peppy** 2020-01-23 13:50 UTC
