### ISSUE TITLE
Add Beatmap Pack IDs to beatmap listing

### ISSUE THREAD

**Issue by FlyingStefan** [ppy/osu-web#5444] opened 2019-12-21 08:44 UTC
Now with the old beatmap listing being gone there's no indication if a beatmap belongs to a pack. For completion purposes but also to manage the beatmap packs more efficiently it'd be great if they would be brought back in the new design.

**Comment by TPGPL** [comment] 2019-12-21 11:22
duplicate of #2025 probably

**Comment by peppy** [comment] 2019-12-25 02:55
Closing as duplicate.

**Closed by peppy** 2019-12-25 02:55 UTC
