### ISSUE TITLE
Adding a Discord username that has an emoji throws an error

### ISSUE THREAD

**Issue by ExillustX** [ppy/osu-web#3401] opened 2018-06-24 05:37 UTC
![image 568](https://user-images.githubusercontent.com/6927114/41816285-d2a97368-7778-11e8-8b4e-2dae73e43bea.png)

**Comment by peppy** [comment] 2018-06-24 06:17
Thanks for the report. This is a duplicate of #3322.

**Closed by peppy** 2018-06-24 06:17 UTC
