### ISSUE TITLE
2FA for authentication

### ISSUE THREAD

**Issue by solehudin-baharsah** [ppy/osu-web#5197] opened 2019-10-28 12:08 UTC
good afternoon
I have a suggestion for two-factor authentication (2FA) to make it easier for osu players! and prevent the sale of accounts and any of rule-breaking rather than receiving a verification code.
I ask for your attention so that this can be realized
as for the cons of this, can give a reason
thank you

**Comment by LiquidPL** [comment] 2019-10-28 12:12
Duplicate of #5163.

**Comment by solehudin-baharsah** [comment] 2019-10-28 12:13
I Am sorry for this. but is avail now

**Comment by STCapricorn** [comment] 2019-10-28 12:13
Duplicate of #5163

**Comment by solehudin-baharsah** [comment] 2019-10-28 12:14
@LiquidPL but  2FA authentication can replace email verification for changing password?

**Comment by solehudin-baharsah** [comment] 2019-10-28 12:18
2FA I mean is similar to Google authentication
Barcode scan or type Token and done!

**Comment by solehudin-baharsah** [comment] 2019-10-28 12:18
I Am sorry for my bad english.

**Closed** 2019-10-28 12:39 UTC
