### ISSUE TITLE
BBCode field

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3038] opened 2018-04-18 18:06 UTC
I've seen #2335, it's a bit related, though I wasn't sure if should comment my whole "issue" below.

![chrome_2018-04-18_19-53-58](https://user-images.githubusercontent.com/32525896/38949297-44fe4eae-4342-11e8-8fd6-7fa39a06da13.png)
That's what we currently have. If you ask me, we could add colors and more of BBCode.

https://osu.ppy.sh/help/wiki/BBCode
- numbered list isn't really needed since people usually use [list] only

add ...
- underline
- spoiler
- spoilerbox (?) - can't tell if people prefer using [box] or [spoilerbox] ...
- quote
- code
- centre
- profile (?)
- notice - I don't even know why this wasn't listed on the old page.

My last thoughts on this are to add a hyperlink to https://osu.ppy.sh/help/wiki/BBCode so that people can get used to it. Also, icons for every bbcode looks cool, but I think in tags it was better to understand (?)

**Comment by Xinnoh** [comment] 2018-04-19 00:47
duplicate of #2357

**Comment by peppy** [comment] 2018-04-19 01:15
We likely won't be continuing to add more bbcode as our eventual plan is to switch to markdown (it is a better and more understood standard these days).

Closing as duplicate of #2357.

**Closed by peppy** 2018-04-19 01:15 UTC
