### ISSUE TITLE
Approved maps not showing up using the 'ranked=<year>' setting

### ISSUE THREAD

**Issue by ilucaa** [ppy/osu-web#7498] opened 2021-04-17 13:54 UTC
Self explanatory, approved maps not showing using the ranked=<year> setting on beatmap search.

Shown below is the search with the setting:
![image](https://user-images.githubusercontent.com/51536354/115115567-68c14a80-9fbf-11eb-9c70-4a4dd2d965c0.png)

Shown below is the search without the setting and the map that it's supposed to show:
![image](https://user-images.githubusercontent.com/51536354/115115583-7d054780-9fbf-11eb-974e-ec438b0bf8d2.png)

Don't know if this is intentional or not - but I would assume not.

**Comment by peppy** [comment] 2021-04-17 14:22
Probably a duplicate of https://github.com/ppy/osu-web/issues/7483.

**Closed** 2021-04-19 04:35 UTC
