### ISSUE TITLE
Scrolling issue sometimes appears when switching panels due to the text editor being pinned

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2168] opened 2018-01-04 07:31 UTC
https://streamable.com/yxnuq

**Comment by nanaya** [comment] 2018-01-04 07:39
can't reproduce.

**Comment by peppy** [comment] 2018-01-04 07:40
another turbolinks issue maybe?

**Comment by Xinnoh** [comment] 2018-01-04 08:54
i can't reproduce it either, it's really random when it appears, bug has been around for a while

**Comment by nekodex** [comment] 2018-01-11 10:51
I'll close this for the time being. If you can reproduce or find any clues, feel free to reopen.

**Comment by Xinnoh** [comment] 2019-02-04 11:17
i can still do the bug

**Comment by Xinnoh** [comment] 2019-02-04 11:18
ok figured it out, it only happens when i have the chrome extension grammerly enabled
not sure if this is important to fix anymore

**Comment by peppy** [comment] 2019-02-05 02:16
I think in a case like this it is probably not our responsibility to fix (unless it has the potential to affect many common extensions)

**Comment by notbakaneko** [comment] 2019-02-05 05:44
We can't be fixing issues caused by extensions that run their own script hooks and mess about with the page layout.

**Closed by notbakaneko** 2019-02-05 05:44 UTC
Labels: browser issue, bug, modding discussions
