### ISSUE TITLE
Prefix link `/wiki/` is disappeared on BN General Information

### ISSUE THREAD

**Issue by mousesalt** [ppy/osu-web#7693] opened 2021-06-05 09:25 UTC
currently, the `/wiki/` on [EN] [BN General Information](https://osu.ppy.sh/wiki/en/People%2FThe_Team%2FBeatmap_Nominators%2FGeneral_Information) that should be stated to the site is disappeared 
but in the GitHub osu-wiki is already stated.

![](https://cdn.discordapp.com/attachments/218677502141399041/850638085167382578/unknown.png)

**Comment by DoryanR** [comment] 2021-06-05 09:38
Just to add a few things:
- Hovering over the first link in the article (and on other links in this article as well), the `/wiki/` prefix is not present, and when clicked, the link sends us to an error page.

![2021-06-05 11_26_50-](https://user-images.githubusercontent.com/55928127/120887193-c05c5980-c5f1-11eb-98d2-c4481617b678.jpg)

![2021-06-05 11_34_03-missing _ osu! – Brave](https://user-images.githubusercontent.com/55928127/120887258-09aca900-c5f2-11eb-9a50-e32e99cf9578.jpg)

- However, if you check the page on GitHub, the link is correct and redirects to the right place.

![2021-06-05 11_27_27-Editing osu-wiki_en md at master · ppy_osu-wiki – Brave](https://user-images.githubusercontent.com/55928127/120887204-ceaa7580-c5f1-11eb-8613-8623aac1bc7b.jpg)

**Comment by bdach** [comment] 2021-06-05 09:41
This is some funny business related to URL encoding, which makes sense as the URLs in questions are relative and use `..` parent traversal in particular. If I visit

```
https://osu.ppy.sh/wiki/en/People%2FThe_Team%2FBeatmap_Nominators%2FGeneral_Information
```

the links are broken. However if I visit

```
https://osu.ppy.sh/wiki/en/People/The_Team/Beatmap_Nominators/General_Information
```

the links are fine.

**Comment by gagahpangeran** [comment] 2021-06-05 13:41
That's right. It's the URL encoding problem.

Now the next question is, how @mousesalt can get into that page with that broken URL encoding. I can't reproduce it by just opening wiki main page > click 'Beatmap Nominators' in People section > click 'General information for Beatmap Nominators' on top of the pages.

**Comment by mousesalt** [comment] 2021-06-05 13:55
i can't get into that broken link as well. it's the same problem like at you all.

**Comment by gagahpangeran** [comment] 2021-06-05 14:04
So, how did you get that link in the first place?

If this is something that you can't reproduce consistently other than visit that page directly using that broken link, then I think this issue is out of scope.

**Comment by mousesalt** [comment] 2021-06-05 14:10
just visit through main wiki page and write the page desire.

**Comment by gagahpangeran** [comment] 2021-06-05 14:14
Ah, so the issue is broken suggestion link.

**Comment by peppy** [comment] 2021-07-20 08:40
This looks to have been resolved (not sure why it wasn't automatically closed).

**Comment by nanaya** [comment] 2021-07-20 08:46
No, it's not fixed yet.

**Comment by peppy** [comment] 2021-07-20 08:46
My bad, misread.

**Closed** 2021-08-02 13:40 UTC
Labels: area:wiki, priority:1
