### ISSUE TITLE
Elements goes out of box in friends list on mobile

### ISSUE THREAD

**Issue by Apis035** [ppy/osu-web#7392] opened 2021-03-30 11:09 UTC
Users with long names or have many elements to display such as multiple badges (BN, ALM), 3x supporter icon, will go out of the box to the right.

![image](https://user-images.githubusercontent.com/53115851/112979364-abdb8b00-9182-11eb-93cc-eb0e63ce7a5d.png)
The 3 dots button goes out and can't be clicked.

Display resolution is 720x1600 if that helps.

**Comment by nanaya** [comment] 2021-03-30 11:18
Duplicate of #6517.

**Closed by nanaya** 2021-03-30 11:18 UTC
