### ISSUE TITLE
storyboard icon didnt appear on website when map using beatmap specific storyboard instead of .osb

### ISSUE THREAD

**Issue by Furozzu** [ppy/osu-web#9930] opened 2023-03-02 11:40 UTC
as said in the title, storyboard icon didnt appear when storyboard use only beatmap specific sb (only storyboarding in .osu file instead of .osb and .osu)

example of the problem: https://osu.ppy.sh/beatmapsets/1122590

**Comment by nanaya** [comment] 2023-03-02 11:48
Duplicate of #9654.

**Closed by nanaya** 2023-03-02 11:48 UTC
