### ISSUE TITLE
text in textarea inside discussion-new__message gets cut off

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#2088] opened 2017-12-23 16:09 UTC
!["cutoff"](https://cdn.discordapp.com/attachments/318028997969838080/394156012707250176/unknown.png)

!["ex2](https://puu.sh/yMtax/875d4fa43f.png)

The textarea inside the newmessage box gets cut off by the new message box pretty hard. 
If you just want to quickly fix this, adding min-height to the new__message container would probably work:
```css
.beatmap-discussion-new__message {
min-height: 60px;
}
```
Otherwise i'd imagine you want it to fit the textarea's contents as people write stuff?

**Comment by peppy** [comment] 2017-12-23 16:12
What browser are you seeing this in? Do you have any custom user styles?

**Comment by Okorin** [comment] 2017-12-23 16:21
Google Chrome Version 63.0.3239.108

**Comment by notbakaneko** [comment] 2017-12-23 17:09
did you use the browser's back function on the site? I think this is caused by the same thing that causes https://github.com/ppy/osu-web/issues/2021

**Comment by Okorin** [comment] 2017-12-23 17:14
seems like i did? reopening the browser through any link like https://osu.ppy.sh/beatmapsets/705741/discussion makes it work fine but going back breaks it?

**Comment by nekodex** [comment] 2018-02-09 11:11
Looks like this was fixed by #2255

**Closed by nekodex** 2018-02-09 11:11 UTC
Labels: bug, modding discussions
