### ISSUE TITLE
Follower counting bug Turkish

### ISSUE THREAD

**Issue by charmfox** [ppy/osu-web#3840] opened 2018-10-27 16:03 UTC
"When set the page to english, it shows normally the users that "follow" you but, when set to portuguese the followers count becomes 1."

same problem is vaild in Turkish language

**Comment by TPGPL** [comment] 2018-10-27 16:04
duplicate of #2067?

**Comment by TPGPL** [comment] 2018-10-29 12:28
should be closed i guess

**Closed** 2018-10-29 13:00 UTC
