### ISSUE TITLE
BBCode closing tag recognition issue

### ISSUE THREAD

**Issue by Spkz** [ppy/osu-web#1666] opened 2017-11-01 17:51 UTC
Some BBcode tags work strangely when using new lines (tested with `[b][/b]` and `[i][/i]`). Somehow the closing tag is not recognized if it is written in a new line/paragraph and tags just won't work then, unless the closing tag is written in the same line. However, `[notice][/notice]` works fine.

Example for the strange behaviour:
![BBCode](https://spkz.s-ul.eu/Z1x36vpD.png)
![Result](https://spkz.s-ul.eu/zPHV8VxH.png)

Example for the currently working behaviour:
![BBCode](https://spkz.s-ul.eu/jA5Wmo8W.png)
![Result](https://spkz.s-ul.eu/4ppCYU5K.png)

**Comment by benpigchu** [comment] 2017-11-02 16:13
【 see #268  】

**Comment by kj415j45** [comment] 2017-11-03 10:48
@benpigchu , ~~you may note it is `duplicate`~~

well, i suppose new osu!web prase BBCode by **line**, so cross lines BBCode Mark won't work properly.

**Comment by Spkz** [comment] 2017-11-03 11:21
@kj415j45 , Regardless, that should not be the expected behaviour anyway, especially when some tags work cross-lines just fine.

~~_And also sorry, I used search before posting this issue but I would've never thought that some issues still stand for almost 2 years now, so I guess I didn't really dig myself deep enough into the results._~~

**Comment by peppy** [comment] 2017-12-04 03:25
Closing as duplicate of #268

**Closed by peppy** 2017-12-04 03:25 UTC
