### ISSUE TITLE
Display people who favourited the map on beatmap page v2?

### ISSUE THREAD

**Issue by zev77** [ppy/osu-web#1781] opened 2017-11-20 11:33 UTC
hello using github for the first time here,

I've asked mappers/the community a bit around and there seems to be a decent demand for displaying which people favourited map just like beatmap page v1

Is this ever going to comeback? It was one of those things i really liked, if not? then this is just an idea.

**Comment by nanaya** [comment] 2017-11-20 11:40
Hi, this is duplicate of #1692.

**Closed** 2017-11-22 04:28 UTC
