### ISSUE TITLE
Add forum update polling

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3284] opened 2018-05-29 16:59 UTC
![chrome_2018-05-29_18-54-21](https://user-images.githubusercontent.com/32525896/40673333-caf3e5ba-6371-11e8-87da-c7da38962e3e.png)

Would it be possible to let the site reload when clicking on this where my cursor is pointing on? (how is it called...?)
I used to click on this when "waiting" for replies. 

pretty low priority

**Comment by peppy** [comment] 2018-05-29 21:08
Disagree; instead replies should be automatically polled for. This is planned eventually.

**Comment by nanaya** [comment] 2018-05-31 02:16
Duplicate of #225.

**Closed by nanaya** 2018-05-31 02:16 UTC
Labels: forum, ux
