### ISSUE TITLE
Symbols concatenated to the plain URL are hyperlinked in chat

### ISSUE THREAD

**Issue by ubinici** [ppy/osu-web#7381] opened 2021-03-27 12:17 UTC
The title might be confusing, so I'll try to explain with visuals here. 

![](https://zeu.s-ul.eu/measbrbg.png) 
![](https://zeu.s-ul.eu/vzjsIR5n.png)

As can be seen above, when a parenthesis symbol is added next to the URL, it redirects to a broken address. Parentheses symbols, in particular, are not valid URL elements, and thus should be exempt from this factor. 

I haven't conducted an in-depth test yet, but there might be other symbols resulting in such a weird situation as this, hence the title.

**Comment by nanaya** [comment] 2021-03-27 16:51
This is probably duplicate of #7347.

**Comment by notbakaneko** [comment] 2024-06-20 20:36
Should be fixed with the change to using markdown

**Closed by notbakaneko** 2024-06-20 20:36 UTC

**Comment by cl8n** [comment] 2024-06-20 21:31
but this one is about chat, not discussions
(or did chat also get a similar fix..?)

**Comment by notbakaneko** [comment] 2024-06-21 08:37
It's changed in #9872, #10138 and some other PRs for other link formats
