### ISSUE TITLE
two bugs on the website in regards to beatmap listing

### ISSUE THREAD

**Issue by Molly-Sandera** [ppy/osu-web#5858] opened 2020-04-01 14:37 UTC
Problem details: 1: sometimes same maps show up continuously(and the scroll bar gets stuck while scrolling with a mouse or arrow keys)
2: sometimes when you return to the listing(while its a big list) from a beatmap(with the back button in browser), the listing becomes black with the same scrolling issue

Video or screenshot showing the problem: https://ibb.co/xXnDXcm
https://ibb.co/wwrKHZf

**Comment by Joehuu** [comment] 2020-04-01 18:19
This is probably a duplicate of https://github.com/ppy/osu-web/issues/3368.

**Comment by Molly-Sandera** [comment] 2020-04-01 19:05
> This is probably a duplicate of #3368.

One of the bugs is indeed a duplicate, but someone in the forums told me to report the second bug, since he didn't see anything like it. I decided to report both

**Comment by peppy** [comment] 2020-04-03 07:44
What browser are you using?

**Comment by Molly-Sandera** [comment] 2020-04-03 09:26
> What browser are you using?

Opera browser

**Comment by peppy** [comment] 2020-04-05 04:33
Closing as duplicate. Please open a new issue with more detail on the specific "second case" you mentioned. An output of the console/network log from your browser and confirmation of whether it is reproducible on a different browser is also appreciated.

**Closed by peppy** 2020-04-05 04:33 UTC
