### ISSUE TITLE
Profile cover

### ISSUE THREAD

**Issue by ghost** [ppy/osu-web#5416] opened 2019-12-15 21:17 UTC
Hello, I come to make a suggestion. it would be nice if the osu profile banner was bigger, it occupied a bigger area, see some references that I made.

Thank you. ;)

Original
https://imgur.com/9XGWmZV

Modified
https://imgur.com/VhVsg8F

**Comment by Joehuu** [comment] 2019-12-15 21:29
Duplicate of https://github.com/ppy/osu-web/issues/4201

**Comment by Joehuu** [comment] 2020-03-07 06:48
bump

**Closed** 2020-03-07 07:40 UTC
