### ISSUE TITLE
Page embedding itself

### ISSUE THREAD

**Issue by Axilotl17** [ppy/osu-web#9907] opened 2023-02-24 04:16 UTC
![image](https://user-images.githubusercontent.com/78441708/221090410-5d5fd753-d2df-40d2-afe0-4946a7775eb7.png)

https://osu.ppy.sh/home/download

the "video guide" section just appears to show the same download page again, but with the video embedded in the embedded page? I see no reason for this to be intentional, it should just embed the video to begin with.

**Comment by Axilotl17** [comment] 2023-02-24 04:19
https://user-images.githubusercontent.com/78441708/221090778-f5093b22-246b-4e1d-bbe1-9f54af0a06eb.mp4

It seems this isnt't replicatable? as in, my friend visiti

**Comment by Joehuu** [comment] 2023-02-24 06:21
Duplicate of https://github.com/ppy/osu-web/issues/9730

**Closed by Joehuu** 2023-02-24 06:21 UTC
