### ISSUE TITLE
Ability to see deleted difficulties in modding discussion interface

### ISSUE THREAD

**Issue by osuShiro** [ppy/osu-web#2002] opened 2017-12-16 08:00 UTC
As per discussed in #osu-web-modding, when a difficulty gets remapped, all mods previously given to it become irrelevant and need to be deactivated in some way.

Current solution for this: delete the difficulty, then reupload the new one. This will allow a fresh difficulty to be made with no modding history. Problem is, it loses the mods given on the previous diff, while the mapper may want to be able to still access them.

Proposed solutions for this:
- add an "archived state" for those mods where only mapper (and QAT/BNs) can see the mods but nobody can reply
- add a detection for deleted difficulties so that they can retain their history but cannot be interacted with

EDIT: it was pointed out (by Sinnoh) that a user may reset the difficulty, then revert that in order to get a clean slate on their diff and not have to reply to mods they don't like. There should probably be an option to merge two difficulties' histories to counter that ?

**Comment by Naxesss** [comment] 2017-12-16 14:38
Also related to #1814 for reference

**Comment by peppy** [comment] 2018-01-12 01:51
Duplicate of #1814

**Closed by peppy** 2018-01-12 01:51 UTC
Labels: feature, modding discussions
