### ISSUE TITLE
Some of wiki image links don't seem to work

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#6921] opened 2020-12-01 19:33 UTC
Not really sure where to post it but guess osu-web is the most fitting place. Since around yesterday, seems like some image links don't load properly. You can see that images are linked properly [here](https://github.com/ppy/osu-wiki/blob/master/wiki/Tournaments/en.md). ``i.ppy.sh`` links to these are returning 404.

Several people confirmed the issue happens to them as well on osu!dev ``#osu-wiki``.

![](https://venix2.s-ul.eu/o84ukQg4)
![](https://venix2.s-ul.eu/oTVT4isO)

**Comment by Joehuu** [comment] 2020-12-01 19:40
Kinda a duplicate of https://github.com/ppy/osu-web/issues/5990, although it's a different message.

**Comment by nanaya** [comment] 2020-12-03 06:02
Should be fixed now (or eventually).

**Closed by nanaya** 2020-12-03 06:02 UTC
