### ISSUE TITLE
Text display

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu-web#5729] opened 2020-03-08 13:12 UTC
https://osu.ppy.sh/users/1830361
![image](https://user-images.githubusercontent.com/59089206/76163486-375a3680-6192-11ea-96c5-7980755c6031.png)

This user has some text inserted in the link field, which breaks the display of text on the site. It may even seem that the problem is in your screen.

**Comment by bdach** [comment] 2020-03-08 13:49
Duplicate of #5398

**Closed** 2020-03-08 17:51 UTC
