### ISSUE TITLE
[Proposal] Additional of ORIGINAL tag to beatmap listing for osu! originals

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu-web#11502] opened 2024-09-21 09:19 UTC
Suggestion from:
https://www.reddit.com/r/osugame/comments/1fc5h7m/comment/lmayl9t/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button 

Example of what it might look like:
![image](https://github.com/user-attachments/assets/f458dc18-388b-4bed-9210-82a2fda280d6)

peppy said it was okay...

**Comment by Joehuu** [comment] 2024-09-24 06:04
Duplicate of one of the points in https://github.com/ppy/osu-web/issues/9864.

**Closed by Joehuu** 2024-09-24 06:04 UTC
