### ISSUE TITLE
Add users beatmap playcount to beatmap page

### ISSUE THREAD

**Issue by maxjmp** [ppy/osu-web#9024] opened 2022-06-14 12:50 UTC
At the moment to see your playcount for a specific map you have to check "Most played beatmaps" on your profile. Many users have played over thousands of beatmaps so finding the playcount for a specific map requires lots of scrolling, especially to find a beatmap which has a very small amount of plays.

I made a bad mockup of what this could look like:
![5JIm2kW (1)](https://user-images.githubusercontent.com/98040492/173579727-d902e94a-1556-48af-87ae-fac8b2e8721c.png)

This would allow users to check their playcount on a map without potentially scrolling really far to find it.

**Comment by NoffyNoffeh** [comment] 2022-06-14 13:00
Basically a duplicate of https://github.com/ppy/osu-web/issues/7423

But I think your mock up does really well at suggesting a simple place it could go where discussion stalled on last year

**Comment by peppy** [comment] 2022-06-15 07:01
I'd tend to disagree that putting a local user stat right next to global statistics is a good move. In addition the icon is basically the same as the one above it, leading to a thoroughly confusing UX.

Let's continue to track in #7423. Maybe @arflyte has some thoughts he can add there.

**Closed by peppy** 2022-06-15 07:01 UTC

**Comment by arflyte** [comment] 2022-06-15 07:36
![Figma_220615-163604](https://user-images.githubusercontent.com/3632750/173770085-c336dacf-dd12-4ae6-b1f7-8b153333209d.png)
This is available in the new design.

**Comment by arflyte** [comment] 2022-06-15 08:12
Hmm, I guess it's not clear enough. The screenshot shows global playcount and current user's playcount. I'll try to make it clearer.
