### ISSUE TITLE
Background dim is not working on popups/menus

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#10951] opened 2024-02-01 23:41 UTC
broke recently

https://github.com/ppy/osu-web/assets/62819481/0ccf992d-a3f3-4095-9e34-c08dd4d7fd8d

**Comment by Joehuu** [comment] 2024-02-02 01:13
Duplicate of https://github.com/ppy/osu-web/issues/10940

**Closed by Joehuu** 2024-02-02 01:13 UTC
