### ISSUE TITLE
The browser tab title should have song title before other information

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2439] opened 2018-02-16 05:35 UTC
![screen shot 2018-02-16 at 1 33 15 pm](https://user-images.githubusercontent.com/30382015/36294783-f6bc16da-131d-11e8-8d5f-a4a175ea1b13.png)
First two maps are v1, second two maps are v2. It's not possible to know what each tab is with v2.

**Comment by dorothy3242** [comment] 2018-02-16 05:37
Duplicate of https://github.com/ppy/osu-web/issues/2108

**Closed** 2018-02-16 06:05 UTC
