### ISSUE TITLE
Inconsistency between beatmap fav count and tooltips

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu-web#4114] opened 2019-01-20 07:02 UTC
Example: 
https://osu.ppy.sh/beatmapsets/439917 and https://osu.ppy.sh/beatmapsets/710979
![Example](https://gsculerlor.s-ul.eu/d6Bfe2yR)
![Second example](https://gsculerlor.s-ul.eu/LAUT0nXe)

**Comment by Joehuu** [comment] 2019-01-21 03:09
Duplicate of #1815.

**Closed** 2019-01-23 08:43 UTC
Labels: beatmap listing, bug
