### ISSUE TITLE
Song and Artist name in original language in the beatmap info page

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-web#5967] opened 2020-04-29 13:38 UTC
I think it is necessary to show the original language metadata in the beatmap info page. This seems to be related to https://github.com/ppy/osu-web/issues/3217 but I think the beatmap info page should always provide original info and sources.

**Comment by peppy** [comment] 2020-05-08 07:05
We do really need this, along with a setting to toggle it like in-game.

**Comment by Joehuu** [comment] 2020-05-23 17:37
> I think the beatmap info page should always provide original info and sources.

> setting to toggle it like in-game

A toggle counteracts the “always provide original info and sources”, so this is a duplicate of https://github.com/ppy/osu-web/issues/3217.

**Comment by peppy** [comment] 2020-06-02 06:46
Closing as duplicate of #3127.

**Closed by peppy** 2020-06-02 06:46 UTC
Labels: area:beatmap-listing
