### ISSUE TITLE
Show some indication that a beatmap is spotlighted on its beatmapset page

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#3733] opened 2018-09-30 18:46 UTC
another one from #osu-spotlights

probably just a small icon somewhere that links to the relevant chart

**Comment by Shadowthegod** [comment] 2018-10-01 00:05
Here is some example of how we thought it could look like. Nothing fancy or anything but a small indicator that a map appeared in the Spotlights once. A small star icon next to the ranked text or something. I consider it some kind of reward. 

[Beatmap page](http://puu.sh/BDEH2/4366924b9e.jpg)
[after hover](http://puu.sh/BDESk/1322fbdb8d.jpg)

**Comment by Ephemeralis** [comment] 2018-10-25 04:00
an easy way to handle this would be to take the icon used on the medal and split it out into its own 'token' element instead of just the star, complete with a link to the chart/pack that the beatmap appears in

by design, maps will only appear in one set of spotlights for the most part

**Comment by TheRealStevie** [comment] 2022-11-23 15:33
I think this can be closed as per https://github.com/ppy/osu-web/pull/8768.

**Closed** 2022-11-25 18:05 UTC
Labels: proposal
