### ISSUE TITLE
Suggestion: add link to osu!lazer in download page

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu-web#9356] opened 2022-10-08 14:12 UTC
Currently, if a macOS user goes to [the osu! download page](https://osu.ppy.sh/home/download), they see three download options: the Windows download (which they can't use), a mirror of the Windows download (which they also can't use), and a link that says "macOS users". This link takes them to a website that doesn't have an immediately visible download link, seems overall less official (it's hosted on tumblr), and appears to not have been updated since 2018. This was very off-putting to me when I first found it.

However, macOS players do have access to an official, highly polished, and regularly updated version of osu!: lazer. Unfortunately, to someone who is fist visiting the osu! website, lazer is extremely hard to find without an external search (and even then they'd most likely find the github page, which can also be somewhat off-putting to casual users unfamiliar with it). Because of this, I'd propose that [a link to osu!lazer](https://github.com/ppy/osu) be added to [the download page](https://osu.ppy.sh/home/download), as well as direct links to download the latest release for macOS,  Linux, and maybe also Windows (The Windows link is less important because osu! stable was built for Windows).

**Comment by frenzibyte** [comment] 2022-10-08 14:15
Duplicate of https://github.com/ppy/osu-web/issues/8512

**Comment by Walavouchey** [comment] 2022-10-08 14:16
shouldn't it be this one https://github.com/ppy/osu-web/issues/8246

**Closed by frenzibyte** 2022-10-08 14:15 UTC

**Comment by frenzibyte** [comment] 2022-10-08 14:17
I dunno, I'm seeing one thread referring to updating the download page to match new design iterations, and another thread focusing on adding lazer to the download page itself.

**Comment by Walavouchey** [comment] 2022-10-08 14:19
former contains the scope of the latter, no?

**Comment by Non-Binary-Programmer** [comment] 2022-10-08 14:24
Is there a reason we couldn't/shouldn't, at the least, replace the "for macOS" link on the download page with lazer without redesigning the whole webpage first?
