### ISSUE TITLE
please match recent profile osu! lazer with osu! stable 

### ISSUE THREAD

**Issue by NeofetchNpc** [ppy/osu-web#11481] opened 2024-09-09 14:56 UTC
please add Recent like in osu! stabile view 

Osu! Lazer ( acheatment only ) 
![Screenshot_20240909_215154_Chrome](https://github.com/user-attachments/assets/8aebba25-a333-4d8e-a440-4844e72b5870)

Osu! Stabile ( All )
![Screenshot_20240909_215446_Chrome](https://github.com/user-attachments/assets/a53ee677-6192-4a8a-8b29-f55cc4a670fd)

I hope that in the osu! Lazer web profile display, recent will be the same as in osu! Stabile.

**Comment by cl8n** [comment] 2024-09-10 01:07
looks like duplicate of #11188

**Closed by cl8n** 2024-09-10 01:07 UTC
