### ISSUE TITLE
suggestion for the site (star rating)

### ISSUE THREAD

**Issue by Kuganee** [ppy/osu-web#7153] opened 2021-02-02 21:01 UTC
hello hello, I have a suggestion that more than one player would like to see on the site in order to improve the user experience but also the convenience of the site.
indeed it would be comfortable to add the option "star rating" on the osu! website in order to classify the level of the proposed beatmap, for example in my case I would have liked it to be there in order to select this option in the 6.80-7.90 stars configuration.

**Comment by bdach** [comment] 2021-02-02 21:07
Duplicate of #5998

**Closed** 2021-02-02 21:21 UTC
