### ISSUE TITLE
APIv2 Add a route to post in beatmap discussion

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-web#8435] opened 2021-12-11 20:43 UTC
I'm continuing a project of mine related to modding, and currently the api doesn't allow posting in a beatmap discussion. It would be helpful if I could use this function.

**Comment by notbakaneko** [comment] 2021-12-13 04:40
possibly a dupe of #6073

**Closed by notbakaneko** 2021-12-13 04:40 UTC
