### ISSUE TITLE
Incorrect status on updated beatmap on beatmap info page

### ISSUE THREAD

**Issue by Moeriko** [ppy/osu-web#7464] opened 2021-04-10 17:19 UTC
I don't know if anyone else has had this issue but it occured on my own mapset:
https://osu.ppy.sh/beatmapsets/1368018

You can see that it's updated properly but the tag on the right shows "Graveyarded"
I have tried to reupdate several times a week ago and also now, but it still stay the same status everytime it was updated

For some reason this status is handled properly if I check it in my user page under pending beatmaps:
https://osu.ppy.sh/users/5075660

I hope this does not affect nomination process

**Comment by NoffyNoffeh** [comment] 2021-04-10 17:45
After checking out the thread https://osu.ppy.sh/community/forums/topics/1242977 there seems to be a redirect loop, confirmed by multiple people. It looks like issues with the thread may be causing problems with the map status.

@peppy  would probably need to fix this on his end. 

For reference though was there other weird behavior that lead to this? So that whatever caused the issue can be addressed/fixed in general.

**Comment by Moeriko** [comment] 2021-04-10 21:16
No, all I did was log on as usual and update the map, I don't remember doing or seeing anything unusual other than that

**Comment by peppy** [comment] 2021-04-16 05:29
@Moeriko we have a fix incoming to stop the redirect loop, but I've also repaired your beatmap. Can you try submitting it once more and ensure everything looks okay?

**Closed** 2021-04-16 08:47 UTC
