### ISSUE TITLE
Allow joining chat channels from web

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#7048] opened 2021-01-08 10:32 UTC
Currently, when a player joins a few chat channels from the lazer client, the joined channels will show up on the web chat interface. However, there is no explicit way to join a chat channel from web.
We could probably do this by adding an add button below all chat channels.

**Comment by Joehuu** [comment] 2021-01-08 13:44
Duplicate of https://github.com/ppy/osu-web/issues/4661

**Closed by Joehuu** 2021-01-08 13:44 UTC
