### ISSUE TITLE
Suggested restructure to stable's current map slot system

### ISSUE THREAD

**Issue by Penguinosity** [ppy/osu-web#7974] opened 2021-08-04 16:08 UTC
[Link to the mirrored post on stable forums](https://osu.ppy.sh/community/forums/topics/1388182?start=8228229)

Hello, I'm here to spread a feature request that me and many other players feel would greatly benefit numerous areas of the game. That addition being, to either have the ability to upload maps directly to the Graveyard (limiting it to "reputable" users), or the ability to send Pending maps to the Graveyard. I’ve been told that the “bss” wasn’t intended for something like this, along with the fact that I’m more than aware Lazer is highest priority for everyone. I’m ignorant to how much work it would take to implement this, but I would like to plead the case if there’s a possibility here, as I know many would gain from the inclusion.

To start, this addition would improve the mapping landscape and overall ease for players outside of the game to come and share their content. Personally I can only speak as a mania player, but from what I’ve seen this is where this situation holds the most relevance. As the current system stands, the number of maps that you can upload is incredibly restricted. The people who have been creating content in other games for years (i.e., Etterna, Quaver, o2jam) are prevented from migrating their content in mass and instead need to wait months just to get a chunk of their work over to osu. The alternatives present are to either upload said content through a media sharing site, or to create “packs”, both of which are less than ideal for most people. On one hand, the maps are not even accessible through osu directly and on the other, a mapper is forced to work around the janky constraints of how making a pack works on osu to begin with. Not to mention that in a packs case, players would be forced to download something that may only contain a fraction of content they’re actually interested in. The pack format for many people has been a way to cope with the upload limitations, rather than being the decision that they wanted to actually make. If this may sound overblown, I would implore anyone who isn’t savvy with these other rhythm games to take a look at the library of maps there, and just how many have come from single individuals. _Forcing_ people who have created so much material to turn to these alternatives because they don’t want to wait indefinitely, seems hardly fair.

Now another reason this feature would be great, is for isolated events that reach out to mappers on a whim needing some kind of change on a map in question. As a Loved captain and staff member of multiple tournaments in the past, I can say that I’ve seen this come up an innumerable number of times. **_The mapper in question has full slots and can’t revive a map?_** Well, the only options are to either wait if the time frame allows it, upload the map yourselves (assuming a tournament situation), or to bother a GMT and see if they will move something to the Graveyard manually. This moving maps to the Graveyard or being forced to wait scenario is especially relevant to Loved, and multiple recent examples can be given if need be. It’s become more confusing over time as to why it has to be like this, and the inconvenience has been a detriment on all fronts. When tournaments end up having to upload something themselves, the majority of the time those uploads are deleted post-event, which leads to the index archive missing map links. As for Loved, the bottom line is it just causes everything to run behind.

These are the two biggest points that I just wanted to discuss. From asking others, it seems that this limitation was set in place to prevent players from dumping mass amounts of potentially low quality/unfinished content into the game and flooding the Pending, or the Graveyard section if players could just submit to it willy-nilly. Preventative measures need to be in place so that this doesn't happen. It’s because of this that I know the solution wouldn’t be to just turn the Graveyard into the junkyard, but maybe create some kind of middle ground here. I’ve just come up with a number of alternatives myself that I would like to share, and all of them keep the current Pending slots number untouched.

**1.** Add the ability to upload maps directly to the Graveyard, limiting it to only users who are proven to be reputable (have Ranked or Loved a Beatmap, or are a part of the staff team)

**2.** Add the ability to Upload/move Pending Beatmaps to the Graveyard, and mirror the maximum slots a player has in Pending, to the Graveyard. This effectively doubles the number of "active" uploads a player can make.

**3.** Give players the option to move any of their maps in Pending directly to the Graveyard as above, but add a cooldown each time you can do this (24 hours or something).

**4.** Significantly decrease the current 4 week period it takes for a map to automatically move from Pending to Graveyard

**Comment by peppy** [comment] 2021-08-04 16:31
One thing to note: "graveyard" is not to be considered as permanent storage. Maps are purged from that currently. It sounds like you want it to be treated as such, which goes against its intention.

I think what you're *also* asking for here is the ability to mark maps as "not for ranking" without them being graveyarded.

I believe the use case of "migrating content from other game" is quite rare, as well. This is the first time I've heard of such a thing. Most beatmaps are made via osu! tools because osu! has different quality standards to other games. Which is also another reason that the upload limit is imposed (to guide mappers towards aiming for ranked status).

**Comment by Penguinosity** [comment] 2021-08-04 17:29
Thank you for getting back to this post so quickly. I’ll try to better explain some aspects of what I was mentioning here if that can help further anything along, and also clarify what was originally being proposed. 

As I had said somewhere in the write-up, I can only speak confidently as an o!m player/mapper/tournament staffer, and a player of other various VSRG games similar to it. The mapping philosophy that the majority of players from this scene follow (this is including most of our most prolific members), is that bending all works to fit under the guise of ranking criteria shouldn’t be necessary and more often than not it’s preferred for all parties to leave a map as it was originally created/intended. I believe even any BN for any gamemode in fact would attest to this. So, I’m unsure if this entire premise is something that you disagree with entirely (and if that’s the case this is unfortunate), but it’s a huge factor to the reason why a map slot rework would be greatly appreciated by many people. Ranked maps are crucial to the development and prosperity of osu, but I know that the content made without ranked intentions holds just as important of a place.  

If I can just quickly clarify and respond to the few things you said I'll do that. I don’t have much to say for the Graveyard "not being permanent storage", as that’s always the way me and others who I know have treated it when the map we created was not made solely for the intention of being Ranked. Almost all tournament picks these days are unranked maps, and that's because they hold the most competitive viability. There's a lot going into why this is, but that's a topic for another place. I would definitely like to hear more about this though, as wanting everything to go for Ranked might just be a conflict of interest between the player-base and development front. I’ll move on though and try to better describe and go into other details.

The ability to mark maps as “Not for Ranking” would be great if it were under the premise that it functioned beyond just a label. Say marking a map as not for Ranking meant that it would move quicker from Pending to Graveyard or something of that sort. I would see that already as a big improvement to helping this dilemma. Second, the amount of migrated content that comes into the game, and just how much I can’t overstate its scope is something that I need to get across. I can confidently say that most of mania’s most impactful content has come from outside of its own community (see things like [Yolomania](https://osu.ppy.sh/beatmapsets/243027#mania/560739) or any other pack/map listed as “convert”, anything from [Icyworld](https://osu.ppy.sh/users/1383951), or anything from [Shoegazer](https://osu.ppy.sh/users/2520707) for example). These are people who spend the majority of their time creating maps for other games, but still put in the time to share what they make with the osu players. See also the countless amounts of manual and extensive “Convert” libraries that the community has put together over the years ([This](https://osu.ppy.sh/community/forums/topics/399593), or [this](https://osu.ppy.sh/community/forums/topics/684032)) and plenty of others can be listed too. I could also spend time listing out just how large the amount of content that’s _already_ in osu is, that came from different games if that’s necessary to not make this seem overblown. I can promise that without all of this content that the gamemode and community would not be what it is today. 

Anyways I do again appreciate how quick the response was, as I know you're constantly busy on the development front for Lazer. If there's something that can be done here in anyway though to try and reach some kind of middle ground, it would mean a lot to many players.

**Comment by Adrriii** [comment] 2021-09-07 18:41
Peppy: As a long time player and being part of the community I feel like I can bring you some feedback as to how we perceive and play the game, reading your answer I feel like you missed out on what osu!mania is for us. I'll try to be as helpful as possible while justifying what I'm trying to get across.

**About the graveyard**

I can confirm that for **many** people in osu!mania and especially at higher levels, playing ranked charts really is not the norm. Newly ranked charts make us curious and we take a glance at them, maps that allow farming will be played on a regular basis for those who take an interest in performance points (that is, not everyone really). Some maps with leaderboards have a competitive aspect to them, mostly Loved maps to be honest. And by competitive I mean, on a per-map basis. Which is way more interesting if the map has a lot of gimmicks, peculiar skill requirements etc. Unfortunately, these maps are often those who will not be considered rankable, either because of the "quality", criterias and such. Even if ranked maps can be considered "more qualitative", the content that can be found in the graveyard will never ever be matched by the ranked section as we know it.

To push a map for ranked, the mapper needs to take lengthy extra steps that will most likely alter the original work. The reason mappers make maps, is for the enjoyment of people and probably their own as well. If this goal is already reached in the graveyard, there is no need to go further than that - especially if going for ranked would nullify the achievements by the mentioned alterations.

In my opinion this is these factors that creates the current situation ; higher level osu!mania players play graveyarded maps more than the rest, at the very least on average. Though the Loved section is more and more popular for this as well. You may have the stats to contradict me or back me up, because what I am pointing only results from a shared sentiment, either way I hope you can now better understand this aspect of how we play the game.

Now, you mentioned that graveyarded maps are purged. I am not sure what you mean by that, but it sounds scary. As I've said, graveyarded maps make up for the most part of our enjoyment as players, and in itself it forms an extremely huge "legacy" (in the best of forms), even more important _in my opinion_ than the ranked section. I fail to understand this part as what I get seems unreasonably harsh on the mappers, so this must be something else I don't get.

**About migrating content from other games**

Now I get that for osu!standard, migrated maps are a strange idea. But osu!mania is a VSRG, and it's very far from being the only one. Previous and also current games offer an immense amount of content that is far from being neglectable. Penguinosity linked you to resources in the osu! forums about migrated packs, I think I can add an interesting visual to help you understand how HUGE migrated content actually is. So huge in fact that it's unreasonable to try to upload them in osu!, which is why we use other means such as Google Drive, Dropbox and others to share these pieces of work between ourselves. Currently, PatouZ is on the tracks to create a google spreadsheet listing with an important amount of packs, since this is a work in progress it is not available  for the public yet but he agreed to offer a visual to understand the scale of even an incomplete "collection of collections" : 

https://user-images.githubusercontent.com/16978299/132394028-2981a719-77f8-4167-bce2-785be533c077.mp4

All of these packs roughly contain 10 maps on average, some going up to 100 maps and usually spanning from 100MB to multiple GBs. I have confirmation that some of these packs were made in osu!, but for the huge majority they were created externally and for the purpose of another game. The very nature and "topic" of most of these packs make them unrankable in the first place, even if in most cases the author also plays osu and would technically be able to push for ranked. Which takes us back to the previous section in terms of players playing unranked so much. As you can guess these packs are unsubmitted, so I'm not sure how you data you can get on that though.

I hope my take was interesting to you, and that it might change how you look at mapping in osu!mania, as well as considering improvements in a way that could make it all better for the players. Thank you for reading.

**Comment by IcyWorldSM** [comment] 2021-09-11 02:47
Osumania is one of the greatest VSRG's of all time, and has many contributing factors that make this true; however your comments about graveyard being non permanent and eventually become purged are alarming. Additionally I understand the incentive wishing for mappers to go strictly for ranked status and use osu tools to achieve your quality standards, but this is out of touch with the actual player base and mappers intentions for using osumania. 

First allow me to introduce myself, I'm IcyWorld from the VSRG Stepmania, which has existed since September 21 2001, and I have been a member of the stepmania community since October of 2007, and Osu since February of 2012. Osu released on September 16 of 2007, and I have seen Osumania come to fruition since October 8 of 2012. 

I've watched as Osumania has grown in player base since Day 1, and how the map pool has grown as well in regards to Ranked, Loved, and Graveyard. I've seen the shift of popularity go from nearly all other rhythm games to osumania as this game may have one of the best ways to share content and interact with each other via chat channels and forum posts, naturally this shift would include the conversion of other vsrg content osumania. It's shocking to me that the developer of osumania would be this out of touch with the community that you would state "this is the first time I've heard of such a thing" regarding content migration. 

Let me share some insight to content preservation in stepmania as it is directly related to the perception of graveyard in OsuMania to perhaps every vsrg community that interacts with osumania. Stepmania has never had a 100% centralized means of obtaining stepmania simfiles, we've had to rely on community effort, trust, dedication, and passion for the game to preserve our meaningful and historic past. Prior to 2004, there was not too much original content for stepmania a large quantity of content came from conversions from Dance Dance Revolution. Simfile sharing back then was done in great part through single song downloads via bemanistyle.com and the flashflashrevolution.com simfile database, users could upload as much content as they wanted or could create to these simfile databases. Around 2004 we created our first community collaboration titled Keyboard Megapack, which was largely a compilation of what were the best files up to its release from the simfile data bases. Other packs created in this manner were also put together including Keyboard Megapack 2, Keyboard Collaboration 1 through 3, and Community Keyboard Megapack 1 through 3. These packs are of notable importance being the first of their kind, but also the fact that they are still obtainable to this day, 16 years later with relative ease of access might I add. The simfile databases at bemanistyle.com and the flash flash revolution simfile database are not available, with them gone we have lost an immense amount of content. The FFR simfile database had more than 35,000 songs, and the bemanistyle database had a similar amount. I imagine there are many old players nostalgic and wish it was not to late to play some of the content in those databases. Both of these websites were separate communities largely and the databases were lost in 2009. Single downloads were far less commonplace by 2007 for Stepmania as it was far more efficient to share a single download link for a pack of 10-50 songs, which could be curated to meet a specific level of difficulty, genre, or file type, or anything that the community would like to collaborate to make.

With this ease of sharing content through packs, it also made it easier for us to upload mirror copies of the packs to various websites, such as megaupload, mediafire, or even individually hosted servers like one of our long time members Izzy still hosts at izzy.nu since 2010. There were many more hosting websites throughout the years, and there will be many more to come I am sure as nothing truly lasts forever, but the reliability of access to all our content, old and new, is of notable importance to us in keeping the game alive and thriving. 

There was a remarkable event that occurred with flashflashrevolution that almost cause stepmania to become lost forever as the stepmania and flashflashrevolution communities are so closely intertwined, we are practically one in the same. The website flashflashrevolution.com was shut down on 12-21-2009, our main form of collaboration, and game preservation suddenly vanished without a trace, and with great risk of losing what was then all 7 years of content. This would have been devastating however with the death of the website several others sprung up. Through community effort and sharing, and by the nature of stepmania, our community packs were all stored on our hard drives, we uploaded what we had to file sharing networks to continue the life of Stepmania. In this period, I managed a list of Simfile Packs at the newly created keybeatonline.net, to create a singular access point available for all the community to be able to reference for access to what we have made. I added new and old packs to the list, and kept it as up to date as I could. I couldn't have done this by myself, but there was definitely an important role to be fulfilled with FFR gone. FFR being gone felt like it would last forever, but it was brought back online on 10-9-2010, and with that downtime the game changed forever and our ties to preservation of content were clearer to understand than ever before. 

There is an unspoken understanding for the most part, that if there is any piece of stepmania content, someone old like myself, or others, may be able to share old lost content if you ask for it through a forum post or directly ask the creator of the content. Or more conveniently the current access points of stepmania content being here https://search.stepmaniaonline.net/packs/e or here https://etternaonline.com/packs

If you check these links, you will find nearly 4000 pack uploads, containing anywhere from 1 song, to possibly 100's of songs. This is a baffling amount of content and is only possible through our ties and passion for the game.

When I read that graveyard is not intended as a permanent form of map storage, this frustrated me, was completely unexpected, and excruciatingly disappointing considering the trials the stepmania community has gone through. Osumanias graveyard is akin to the simfile databases I have seen in the past, and you are in a unique and very powerful position. To my understanding if graveyard maps are purged there is no preservation in mind for graveyard maps. It would be disrespectful to the creators to delete this content without notice, and without setting the proper expectation that graveyard is not a permanent storage. I did not find anywhere on the website that graveyard is not a form of temporary storage. I implore you to reconsider graveyards intended purpose for the sake of the community.

With that said, this is all secondary to the main issue we wished to address. 

The osumania community is comprised of multiple communities coming together, as I've mentioned it would be natural that other communities would want to bring their content to osumania as well. Heck even Dance Dance Revolution back in 2001 came to Stepmania, it's just a natural progression and important to understand that it's basically inevitable that there will be community overlap in any game. Every individual will have their own reason for why they would want to do this. 

Take me for example, I want to share what I have worked on the passed 14 years with anyone who enjoys my content, because I have an undying passion for vsrg, and want to share my passion and enjoyment with anyone else that feels the same. Uploading maps to Osu as a form of preservation, but also ease of sharing this content is the primary reason I upload anything at all. I do not care to actively go for ranked or loved, it is not my desire to create any content that would be eligible for ranked or loved. The fact that I have loved content I believe is a testament to the quality that I produce, the community likes to play my creations, and have openly communicated with me when they have wanted to include me in Project Loved; for this I am truly appreciative, every bit of feedback I hear from osumania about my creations is heartfelt and welcome! I create my content the way I want it and I share it as is. I've done this practically since I started making simfiles 14 years ago as I never liked the notion of meeting others criteria, I've rarely contributed to stepmania packs, but I've created several of my own. By my own merit, my own criteria and vision, I've been able to create over 500 simfiles many of which I enjoy playing personally as it is exactly what I wanted in my own creations. It's all part of the fun for me, it's what truly matters to me. The fact that others enjoy what I envision however, that is something beyond my expectations, that is something special, that is something so dear to me, and inspiring, that it makes me want to keep going, to keep creating content and sharing it. In a sense the spark of passion that I feel for VSRG, is reflected as a roaring, enormous and unmissable inferno in the community. 

I want to share more content with osumania, more than what pending will allow. I want to upload all of my content, I've wanted to do this for years, and the community wants it to. Not just my content from stepmania, but other communities and other users in stepmania too. Osumania is one of the greatest VSRG's of all time, possibly the greatest right now, and this is all thanks to the player base, the content, and especially to you Peppy for having created the game. If any one of these things were missing it would fall apart. 

With this all being said, it is understandable that unlimited uploads that go straight to graveyard would be an incredible privilege, and could be abused. I feel a middle ground can be reached somewhere, I hope that you will put some thought to it, and that this bit of history could be insightful. Please feel free to ask me any questions as well.

**Comment by peppy** [comment] 2021-09-11 02:54
Thanks for all the essays. I'm going to close this thread for now as no further responses are needed. I don't have time to even begin to discuss the issues at hand here (there's a lot to unpack and a lot of equally alarming text in the responses) so I've disable graveyard purging for now and will revisit at a later date.

**Comment by peppy** [comment] 2021-09-11 03:56
Closing in favour of forum thread. Maybe we need to turn on github discussions on osu-web too at this point? I still think forums work better for game system discussions for now, though.

**Closed by peppy** 2021-09-11 03:56 UTC
Labels: proposal
