### ISSUE TITLE
Minor: User and Login dropdown 'glitches' when toggled too quickly

### ISSUE THREAD

**Issue by claudiodekker** [ppy/osu-web#54] opened 2015-09-05 10:59 UTC
https://github.com/ppy/osu-web/pull/50#issuecomment-137892606

> Found an issue - if you repeatedly click on your avatar to show/hide the dialog too fast, the page progressively gets dimmer and dimmer.

Turns out it's a minor issue already in existence (not introduced with my commit) related to the login modal. 

Other than that, it doesn't block user experience in general usage. Don't consider it anywhere near important, fix other things first.

**Comment by PieInOblivion** [comment] 2015-09-07 10:39
No one has acknowledge my contributions so far, why would it change now, but I'll say what I'll say anyway...

Found the simple issue and have a simple solution.
The issue is the transition timer 0.15sec. When the login is pressed, the page creates a 'modal-backdrop fade in' class inside a div it creates, which it then fills with the opacity. If the user then presses away from it (Or on the login button, closing the popup) the timer starts again and after deletes the div. The problem here is that while the timer is going (0.15sec) you press the login again and it creates another div which restarts the same timer, and since the last div deletes when the timer ends, it doesn't remove the div because the timer never ended, it just started again for a new div and therefore stacks as well.

Solution:
Have a timer created for each div rather than 1 timer.

Discussion:
Bit of an odd solution but thats what I came up with on the spot that I think would be easiest. Obviously this wasn't intended and is only a small error but since you noticed it, other people probably will too. But since the topic has been uncommented on for 2 days now, no one must be in a rush to fix it.

**Comment by claudiodekker** [comment] 2015-09-07 19:21
Well, the issue is basically two words: Race conditions.

I didn't really bother explaining it, as that anyone experienced enough to create and implement a proper a fix for this would've recognized it straight off the bat anyway. But yes, it's pretty much exactly what you mentioned.

---

As for as your solution, that won't work. The reason for this is that this issue isn't created by our code*, but rather by the [Bootstrap framework] (http://getbootstrap.com) that powers that modal. In normal usage, the 'trigger' for the modal would hide behind the overlay, which wouldn't allow this to occur. 

Instead, the way we're implementing it, is that the avatar (our trigger) is on top of the model, hence the possibility of clicking it in rapid succession.

Fixing this your way would mean we'd need to change the code of the Bootstrap package, which we can't just go ahead and do, as updating manually modifying the 'core' of a package is pretty much against the rules of sanity, and should be avoided at all times.

The proper way to fix this, is to find either a way to trigger the modal remotely (middle-layer function that calls the modal or ignores the call when in already in progress), or as most developers would do, is look at the package's [official documentation] (http://getbootstrap.com/javascript/#modals-events) and notice the following bits:

Event Type | Description
--------------- | ---------------
*shown.bs.modal* | This event is fired when the modal has been made visible to the user (will wait for CSS transitions to complete). If caused by a click, the clicked element is available as the relatedTarget property of the event.
*hidden.bs.modal* | This event is fired when the modal has finished being hidden from the user (will wait for CSS transitions to complete).

```javascript
$('#myModal').on('hidden.bs.modal', function (e) {
  // do something...
})
```

----

As far as people not fixing it, I mentioned in original my issue that it wasn't important, and right now, I'm sure there's other things to do first. 

--- 

On a less related note: This is an open-source (ish?) project, a community thing, so I don't think you should expect anyone's acknowledgement. For those moving osu!web forward, we're all hard at work at this, either for fun/experience or for bounties, and I'm sure nobody is expecting a thank you. Whether your contributions help or not doesn't matter that much, but personally, I don't think you should have an attitude like that, *especially* not in the first line of a comment.

**Comment by PieInOblivion** [comment] 2015-09-08 05:56
After some thought about my comment yesterday, I came to the conclusion that, yes, my idea wasn't a very good one and came up with another. Since it's simple, and I don't have the time to implement it... Don't know where I was going with that.

[Fix]
Exactly as you stated above, disable object trigger until transition timer is finished.
Just what I was thinking, 2 hours after I posted before.

**Closed** 2015-10-13 07:37 UTC
