### ISSUE TITLE
Modding discussions up/downvotes should be more transparent

### ISSUE THREAD

**Issue by JBHyperion** [ppy/osu-web#4504] opened 2019-05-27 00:35 UTC
The beatmap discussions up/downvote suggestion feature has been a great way to get people more involved in modding, but right now it's quite difficult to track where these votes are coming from. The user profile/modding/events link does log these, but I think something a bit more readily accessible would be useful too.

Knowing who up/downvoted a suggestion would help the highlight users on each side of a particular discussion (may be useful for Beatmap Nominators and Nomination Assessment when mediating beatmap vetoes) and also to alert the moderation team to potential abuse cases where users mass upvote specific points.

The up/downvote buttons could expand a list of users on hover - alternatively, it might be possible to filter suggestions by who up/downvoted, in a similar way to how we can filter suggestions by poster using https://hyperion.s-ul.eu/hix4uINF

**Comment by JBHyperion** [comment] 2019-05-27 00:42
Dammit I got sniped by Ephemeral on https://github.com/ppy/osu-web/issues/4503 - the only difference is I included an additional possibility to use the contributor filter (see link) for sorting suggestions by up/downvoters as an alternative / in addition to the hover option.

This was also referenced previously in https://github.com/ppy/osu-web/issues/1747

**Comment by peppy** [comment] 2019-05-28 03:03
Closing as duplicate of #4503.

**Closed by peppy** 2019-05-28 03:03 UTC
