### ISSUE TITLE
Notification part in the header?

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3574] opened 2018-08-11 16:49 UTC
A suggestion

I was thinking about getting notifications on the osu! site when someone replied to your thread or mentioned you in forums or mv2. Also notifications like "new news right there, click here", server issues could be a thing or something, I don't know. There could be a button for it in the header

**Comment by Joehuu** [comment] 2018-08-11 17:26
Might be the same as #1168, but a little vague.

**Comment by peppy** [comment] 2018-09-06 17:30
Duplicate of #1168. It's one of the next things to be tackled for the website.

**Closed by peppy** 2018-09-06 17:30 UTC
Labels: feature
